import {it,expect} from 'vitest';
import fixture from '../../../fixtures/monthly-operations.data.json';
import budget from '../../../fixtures/budget.slide.json';
import {compileSlide,renderSlideSvg} from '../src/index';
const sample=()=>{const s=structuredClone(budget) as any;s.elements=[{id:'txt',type:'text',rect:{x:40,y:40,w:400,h:100},z:1,runs:[{text:'业务 Report\n第二行'}],style:{fontSize:20,fontFace:'Microsoft YaHei',bold:true,italic:true,align:'right',valign:'bottom'}}];return s;};
it('preserves common Office font and both text alignment axes through compilation and SVG',()=>{
 const c=compileSlide(sample(),fixture as any); const n=c.elements.find(e=>e.id==='txt')!;
 expect(n.fontFace).toBe('Microsoft YaHei');expect(n.valign).toBe('bottom');expect(n.bold).toBe(true);expect(n.italic).toBe(true);
 const svg=renderSlideSvg({...c,elements:[n]});expect(svg).toContain('text-anchor="end"');expect(svg).toContain('font-style="italic"');expect(svg).toContain('y="90"');
});
it.each([{fontFace:'anything<script>'},{valign:'diagonal'},{align:'invalid'},{bold:'yes'},{italic:1}])('rejects invalid text settings %o',(style)=>{
 const s=sample();Object.assign(s.elements[0].style,style);expect(compileSlide(s,fixture as any).diagnostics.some(e=>e.code==='INVALID_STYLE')).toBe(true);
});
it('layout style overrides take precedence for font and alignment',()=>{
 const s=sample();s.layoutOverrides={txt:{style:{fontFace:'Arial',valign:'middle',align:'center'}}};const n=compileSlide(s,fixture as any).elements.find(e=>e.id==='txt')!;expect(n.fontFace).toBe('Arial');expect(n.valign).toBe('middle');expect(n.align).toBe('center');
});
it('compiles text-box fill and dashed outline into the SVG preview',()=>{const s=sample();Object.assign(s.elements[0].style,{fill:'#FFF4CC',line:{color:'#B45309',width:2,dash:'dash'}});const c=compileSlide(s,fixture as any),n=c.elements.find(e=>e.id==='txt')!;expect(n.fill).toBe('#FFF4CC');expect(n.line).toEqual({color:'#B45309',width:2,dash:'dash'});const svg=renderSlideSvg({...c,elements:[n]});expect(svg).toContain('fill="#FFF4CC"');expect(svg).toContain('stroke-dasharray');});
it('compiles editable shape text with its fill, outline and typography',()=>{const s=sample();s.elements=[{id:'shape',type:'shape',shape:'roundRect',rect:{x:40,y:40,w:220,h:100},z:1,fill:'#DCEAE8',line:{color:'#155E75',width:3,dash:'dash'},runs:[{text:'形状内文字'}],style:{fontFace:'SimHei',fontSize:18,color:'#123456',bold:true,align:'center',valign:'middle'}}];const c=compileSlide(s,fixture as any),n=c.elements.find(e=>e.id==='shape')!;expect(n).toMatchObject({type:'shape',text:'形状内文字',fontFace:'SimHei',fontSize:18,color:'#123456',bold:true});const svg=renderSlideSvg({...c,elements:[n]});expect(svg).toContain('形状内文字');expect(svg).toContain('font-weight="bold"');expect(svg).toContain('stroke-dasharray');});
it.each(['triangle','diamond'])('renders the %s shape as native SVG geometry',(shape)=>{const s=sample();s.elements=[{id:shape,type:'shape',shape,rect:{x:40,y:40,w:220,h:120},z:1,fill:'#DCEAE8',line:{color:'#155E75',width:2},runs:[{text:'形状'}],style:{bold:true}}];const c=compileSlide(s,fixture as any),n=c.elements[0];expect(n.shape).toBe(shape);const svg=renderSlideSvg({...c,elements:[n]});expect(svg).toContain('<polygon');expect(svg).toContain('font-weight="bold"')});
it.each(['rtTriangle','parallelogram','trapezoid','pentagon','hexagon','star5','heart','plus','rightArrow','leftRightArrow','chevron'])('keeps and renders common PowerPoint shape %s',(shape)=>{const s=sample();s.elements=[{id:shape,type:'shape',shape,rect:{x:40,y:40,w:220,h:120},z:1,fill:'#DCEAE8',line:{color:'#155E75',width:2},runs:[{text:'形状'}],style:{bold:true}}];const c=compileSlide(s,fixture as any),n=c.elements[0];expect(n.shape).toBe(shape);const svg=renderSlideSvg({...c,elements:[n]});expect(svg).toMatch(/<(polygon|path)/);expect(svg).toContain('形状')});
it('renders an elbow connector with configurable arrow heads and no text fill',()=>{const s=sample();s.elements=[{id:'elbow',type:'shape',shape:'elbow',rect:{x:40,y:40,w:220,h:120},z:1,line:{color:'#155E75',width:3,dash:'dash',beginArrowType:'triangle',endArrowType:'triangle'}}];const c=compileSlide(s,fixture as any),n=c.elements[0];expect(n).toMatchObject({shape:'elbow',line:{beginArrowType:'triangle',endArrowType:'triangle'}});const svg=renderSlideSvg({...c,elements:[n]});expect(svg).toContain('<polyline');expect(svg).toContain('marker-start');expect(svg).toContain('marker-end')});
it('renders an elbow connector with a user-adjusted middle segment',()=>{const s=sample();s.elements=[{id:'elbow',type:'shape',shape:'elbow',rect:{x:40,y:40,w:220,h:120},z:1,line:{color:'#155E75',width:2,elbowOffset:30}}];const svg=renderSlideSvg(compileSlide(s,fixture as any));expect(svg).toContain('points="40,40 180,40 180,160 260,160"')});
it('routes connected elbow endpoints through an adjustable five-segment outer corridor',()=>{const s=sample();s.elements=[{id:'source',type:'shape',shape:'rect',rect:{x:80,y:320,w:120,h:80},z:1,fill:'#DCEAE8'},{id:'target',type:'shape',shape:'rect',rect:{x:420,y:120,w:120,h:80},z:2,fill:'#DDEBF7'},{id:'elbow',type:'shape',shape:'elbow',rect:{x:140,y:120,w:340,h:280},z:3,line:{color:'#155E75',width:2,beginConnection:{elementId:'source',side:'bottom'},endConnection:{elementId:'target',side:'top'}}}];const compiled=compileSlide(s,fixture as any),line=compiled.elements.find(e=>e.id==='elbow')!;expect(line.line?.elbowPoints).toHaveLength(6);expect(line.line?.elbowPoints?.[0]).toEqual({x:140,y:400});expect(line.line?.elbowPoints?.at(-1)).toEqual({x:480,y:120});expect(renderSlideSvg(compiled).match(/<polyline[^>]+points="([^"]+)"/)?.[1].trim().split(/\s+/)).toHaveLength(6)});
it('preserves independent departure, corridor and arrival adjustments in compiled preview geometry',()=>{const s=sample();s.elements=[{id:'source',type:'shape',shape:'rect',rect:{x:80,y:320,w:120,h:80},z:1,fill:'#DCEAE8'},{id:'target',type:'shape',shape:'rect',rect:{x:420,y:120,w:120,h:80},z:2,fill:'#DDEBF7'},{id:'elbow',type:'shape',shape:'elbow',rect:{x:140,y:120,w:340,h:280},z:3,line:{color:'#155E75',width:2,elbowStartOffset:24,elbowCorridorOffset:12,elbowEndOffset:36,beginConnection:{elementId:'source',side:'bottom'},endConnection:{elementId:'target',side:'top'}}}];const points=compileSlide(s,fixture as any).elements.find(e=>e.id==='elbow')!.line?.elbowPoints!;expect(points[1].y).toBe(452);expect(points[2].x).toBe(points[3].x);expect(points[4].y).toBe(56);expect(points.at(-1)).toEqual({x:480,y:120})});
it('preserves manually adjusted elbow segments while resolving connected endpoints',()=>{const s=sample();s.elements=[{id:'source',type:'shape',shape:'rect',rect:{x:80,y:320,w:120,h:80},z:1,fill:'#DCEAE8'},{id:'target',type:'shape',shape:'rect',rect:{x:420,y:120,w:120,h:80},z:2,fill:'#DDEBF7'},{id:'elbow',type:'shape',shape:'elbow',rect:{x:140,y:120,w:340,h:280},z:3,line:{color:'#155E75',width:2,elbowPoints:[{x:140,y:400},{x:140,y:452},{x:600,y:452},{x:600,y:72},{x:480,y:72},{x:480,y:120}],beginConnection:{elementId:'source',side:'bottom'},endConnection:{elementId:'target',side:'top'}}}];const points=compileSlide(s,fixture as any).elements.find(e=>e.id==='elbow')!.line?.elbowPoints!;expect(points).toEqual([{x:140,y:400},{x:140,y:452},{x:600,y:452},{x:600,y:72},{x:480,y:72},{x:480,y:120}])});
it('resolves connected line endpoints and renders PPT fill and line transparency',()=>{const s=sample();s.elements=[{id:'box',type:'shape',shape:'rect',rect:{x:300,y:100,w:160,h:100},z:1,fill:'#4472C4',fillTransparency:35,line:{color:'#155E75',width:3,transparency:25,cap:'round',join:'round'}},{id:'line',type:'shape',shape:'line',rect:{x:40,y:40,w:120,h:40},z:2,line:{color:'#155E75',width:3,endArrowType:'triangle',endConnection:{elementId:'box',side:'left'}}}];const c=compileSlide(s,fixture as any),box=c.elements.find(e=>e.id==='box')!,line=c.elements.find(e=>e.id==='line')!;expect(line.rect).toEqual({x:40,y:40,w:260,h:110});expect(line.line?.flipH).toBe(false);const svg=renderSlideSvg(c);expect(svg).toContain('fill-opacity="0.65"');expect(svg).toContain('stroke-opacity="0.75"');expect(svg).toContain('stroke-linecap="round"')});
