import {beforeAll,afterAll,test,expect} from 'vitest';import request from 'supertest';import {Pool} from 'pg';import {randomUUID} from 'node:crypto';import {mkdtemp,rm} from 'node:fs/promises';import os from 'node:os';import path from 'node:path';import {createApp} from '../src/app.ts';import {fixture} from '../src/db.ts';
const pool=new Pool({connectionString:'postgresql://slidebi_app@localhost:5432/slidebi_test'});let storageDir:string;beforeAll(async()=>{storageDir=await mkdtemp(path.join(os.tmpdir(),'chart-data-'))});afterAll(async()=>{await pool.end();await rm(storageDir,{recursive:true,force:true})});
async function context(){const actor=Number((await pool.query("INSERT INTO app.users(identity_provider,external_subject,display_name) VALUES('test',$1,'charts') RETURNING id",[randomUUID()])).rows[0].id);return {actor,app:await createApp({pool,actorId:actor,storageDir,workerEnabled:false})};}
test('blank and template pages keep data private, omit template provenance footers and remain idempotent',async()=>{const {app,actor}=await context(),key=randomUUID();const blank=await request(app).post('/api/slides/blank').set('Idempotency-Key',key).send({title:'空白'});expect(blank.status).toBe(201);expect(blank.body.elements).toEqual([]);expect((await request(app).post('/api/slides/blank').set('Idempotency-Key',key).send({title:'空白'})).body.id).toBe(blank.body.id);const s=await request(app).post('/api/slides/from-template').set('Idempotency-Key',randomUUID()).send({templateId:'budget-comparison'});expect(s.status).toBe(201);const source:any=Object.values(s.body.extensions.chartData)[0];expect(source).toMatchObject({mode:'private'});expect(source.dataSpec.resultSets.find((result:any)=>result.id===source.binding.resultSetId).fields.every((field:any)=>field.name&&field.description)).toBe(true);expect(s.body.elements.some((item:any)=>item.type==='sourceFooter')).toBe(false);expect((await pool.query('SELECT count(*) FROM app.datasets WHERE owner_id=$1',[actor])).rows[0].count).toBe('0');});
test('private chart data is readonly until copied to managed data; managed updates use CAS and protect references',async()=>{const {app}=await context();let s=(await request(app).post('/api/slides/from-template').set('Idempotency-Key',randomUUID()).send({templateId:'budget-comparison'})).body;expect(s.id).toBeTruthy();const cid=s.elements.find((e:any)=>e.type==='chart').id;const input=(await request(app).get(`/api/slides/${s.id}/chart-data/${cid}`)).body,editedPrivate=structuredClone(input);editedPrivate.dataSpec.resultSets[0].rows[0].actual="777";const rejected=await request(app).put(`/api/slides/${s.id}/chart-data/${cid}`).set('If-Match',String(s.revision)).send(editedPrivate);expect(rejected.status).toBe(422);expect(rejected.body.code).toBe('DATA_NOT_MANAGED');let d=(await request(app).post('/api/datasets').send({name:'管理数据',dataSpec:input.dataSpec,preserveResultSets:true})).body;s=(await request(app).put(`/api/slides/${s.id}/chart-data/${cid}`).set('If-Match',String(s.revision)).send({mode:'dataset',datasetId:d.id,binding:input.binding})).body;expect(s.id).toBeTruthy();expect((await request(app).put(`/api/slides/${s.id}/chart-data/${cid}`).set('If-Match','1').send({mode:'dataset',datasetId:d.id,binding:input.binding})).status).toBe(409);expect((await request(app).delete(`/api/datasets/${d.id}`).set('If-Match','1')).status).toBe(409);d.dataSpec.resultSets[0].rows[0].actual="888";expect((await request(app).put(`/api/datasets/${d.id}`).set('If-Match','1').send({name:d.name,dataSpec:d.dataSpec})).status).toBe(200);const current=(await request(app).get(`/api/slides/${s.id}`)).body;expect(current.revision).toBe(s.revision+1);expect(current.extensions.chartData[cid].dataSpec.resultSets[0].rows[0].actual).toBe("888");expect((await request(app).post(`/api/slides/${s.id}/preview`).send({})).status).toBe(200);});
test('multiple charts keep independent bindings; forged inaccessible dataset links are rejected',async()=>{
 const {app}=await context(),other=await context();let s=(await request(app).post('/api/slides/from-template').set('Idempotency-Key',randomUUID()).send({templateId:'budget-comparison'})).body;const first=s.elements.find((x:any)=>x.type==='chart'),second={...structuredClone(first),id:'second-chart',bindingRef:'second'};s.elements.push(second);const source=structuredClone(s.extensions.chartData[first.id]);source.dataSpec.resultSets[0].rows[0].actual='4321';s.extensions.chartData[second.id]=source;s.bindings.second=source.binding;let saved=await request(app).put(`/api/slides/${s.id}`).set('If-Match',String(s.revision)).send(s);expect(saved.status,JSON.stringify(saved.body)).toBe(200);s=saved.body;expect(s.bindings[first.bindingRef].resultSetId).not.toBe(s.bindings.second.resultSetId);const preview=await request(app).post(`/api/slides/${s.id}/preview`).send({});expect(preview.status).toBe(200);expect(preview.body.diagnostics.filter((x:any)=>x.severity==='error')).toEqual([]);
 const secret=(await request(other.app).post('/api/datasets').send({name:'private',dataSpec:await fixture()})).body;s.extensions.chartData[first.id]={mode:'dataset',datasetId:secret.id,dataSpec:source.dataSpec,binding:source.binding};expect((await request(app).put(`/api/slides/${s.id}`).set('If-Match',String(s.revision)).send(s)).status).toBe(404);expect((await request(other.app).put(`/api/slides/${s.id}/chart-data/${first.id}`).set('If-Match',String(s.revision)).send(source)).status).toBe(404);
});
test('public managed sources are readonly for page owner; changing them publishes to independent pages',async()=>{
 const owner=await context(),viewer=await context();let d=(await request(owner.app).post('/api/datasets').send({name:'共享',dataSpec:await fixture(),preserveResultSets:true})).body;await pool.query("UPDATE app.datasets SET visibility='public' WHERE id=$1",[d.id]);const s=(await request(viewer.app).post('/api/slides/from-template').set('Idempotency-Key',randomUUID()).send({templateId:'budget-comparison',datasetId:d.id})).body;expect(s.id).toBeTruthy();const cid=s.elements.find((x:any)=>x.type==='chart').id;expect(s.extensions.chartData[cid].canEdit).toBe(false);expect((await request(viewer.app).put(`/api/datasets/${d.id}`).set('If-Match','1').send({name:d.name,dataSpec:d.dataSpec})).status).toBe(403);d.dataSpec.resultSets[0].rows[0].actual='9123';expect((await request(owner.app).put(`/api/datasets/${d.id}`).set('If-Match','1').send({name:d.name,dataSpec:d.dataSpec})).status).toBe(200);expect((await request(viewer.app).get(`/api/slides/${s.id}`)).body.extensions.chartData[cid].dataSpec.resultSets[0].rows[0].actual).toBe('9123');
});
test('legacy linked pages support chart data and repeated saves',async()=>{const {app}=await context();const d=(await request(app).post('/api/datasets').send({name:'legacy',dataSpec:await fixture()})).body;let s=(await request(app).post('/api/slides').set('Idempotency-Key',randomUUID()).send({datasetId:d.id,templateId:'budget-comparison'})).body;const e=s.elements.find((x:any)=>x.type==='chart');s.extensions.chartData={[e.id]:{mode:'private',dataSpec:d.dataSpec,binding:s.bindings[e.bindingRef]}};for(let n=0;n<2;n++){const saved=await request(app).put(`/api/slides/${s.id}`).set('If-Match',String(s.revision)).send(s);expect(saved.status,JSON.stringify(saved.body)).toBe(200);s=saved.body;}expect((await request(app).post(`/api/slides/${s.id}/review`).send({revision:s.revision})).body.reviewState.status).toBe('reviewed');});
test('chart data choices do not split the page source while editing',async()=>{const {app}=await context();const s=(await request(app).post('/api/slides/from-import').set('Idempotency-Key',randomUUID()).send({dataSpec:await fixture(),templateId:'budget-comparison'})).body;expect(s.id).toBeTruthy();const choices=await request(app).get('/api/datasets?view=chart');expect(choices.status).toBe(200);expect((await request(app).get(`/api/slides/${s.id}`)).body.revision).toBe(s.revision);});
test('ordinary tables use the same private and managed data binding API as charts',async()=>{const {app}=await context(),data=await fixture();let s=(await request(app).post('/api/slides/blank').set('Idempotency-Key',randomUUID()).send({title:'表格页'})).body;const result=data.resultSets[0],fields=result.fields.slice(0,2).map((field:any)=>field.id),tableId='table-data-element',bindingRef='table-binding',binding={resultSetId:result.id,roles:{columns:fields}};s.elements=[{id:tableId,type:'table',rect:{x:60,y:80,w:700,h:260},z:1,bindingRef,fields}];s.bindings={[bindingRef]:binding};s.extensions={chartData:{[tableId]:{mode:'private',dataSpec:data,binding}}};let saved=await request(app).put(`/api/slides/${s.id}`).set('If-Match',String(s.revision)).send(s);expect(saved.status,JSON.stringify(saved.body)).toBe(200);s=saved.body;const privateData=await request(app).get(`/api/slides/${s.id}/chart-data/${tableId}`);expect(privateData.status).toBe(200);expect(privateData.body.binding.roles.columns).toEqual(fields);const dataset=(await request(app).post('/api/datasets').send({name:'表格管理数据',dataSpec:data,preserveResultSets:true})).body;saved=await request(app).put(`/api/slides/${s.id}/chart-data/${tableId}`).set('If-Match',String(s.revision)).send({mode:'dataset',datasetId:dataset.id,binding});expect(saved.status,JSON.stringify(saved.body)).toBe(200);expect(saved.body.extensions.chartData[tableId]).toMatchObject({mode:'dataset',datasetId:dataset.id});});
test('imported business visuals expose all bound template data and re-render from managed edits',async()=>{
 const {app}=await context();
 let slide=(await request(app).post('/api/slides/from-template').set('Idempotency-Key',randomUUID()).send({templateId:'org-chart'})).body;
 const visual=slide.elements.find((element:any)=>element.id==='org-chart-view');
 expect(slide.extensions.chartData[visual.id]).toMatchObject({mode:'private',binding:{resultSetId:'result-org-chart'}});
 const source=(await request(app).get(`/api/slides/${slide.id}/chart-data/${visual.id}`)).body;
 expect(source.dataSpec.resultSets.find((result:any)=>result.id===source.binding.resultSetId).fields.map((field:any)=>field.id)).toEqual(['nodeId','name','parentId','title']);
 const dataset=(await request(app).post('/api/datasets').send({name:'组织结构验证数据',dataSpec:source.dataSpec,preserveResultSets:true})).body;
 slide=(await request(app).put(`/api/slides/${slide.id}/chart-data/${visual.id}`).set('If-Match',String(slide.revision)).send({mode:'dataset',datasetId:dataset.id,binding:source.binding})).body;
 dataset.dataSpec.resultSets[0].rows[0].name='验证项目委员会';
 expect((await request(app).put(`/api/datasets/${dataset.id}`).set('If-Match','1').send({name:dataset.name,dataSpec:dataset.dataSpec})).status).toBe(200);
 const preview=await request(app).post(`/api/slides/${slide.id}/preview`).send({});
 expect(preview.status,JSON.stringify(preview.body)).toBe(200);
 expect(preview.body.elements.some((element:any)=>element.text?.includes('验证项目委员会'))).toBe(true);
});
