import {test,expect} from 'vitest';
import {fixture} from '../src/db';
import {compileSlide,createSlide,renderSlideSvg} from '@slidebi/presentation';
import {writePptx} from '../src/export/pptx';
import {mkdtemp,readFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
import JSZip from 'jszip';
const kinds=['stackedColumn','percentStackedColumn','pie','donut','combo','area','scatter'];
async function model(kind:string){const data=await fixture();const slide=createSlide(data,kind==='area'?'monthly-trend':'budget-comparison');slide.elements=slide.elements.filter((e:any)=>e.type==='chart');const e=slide.elements[0];e.chartType=kind;e.options={showLegend:true,showLabels:true,secondaryAxis:kind==='combo'};const b=slide.bindings.main;b.computations=[];if(['pie','donut'].includes(kind))b.roles.series=['actual'];if(kind==='combo')b.roles={categoryKey:'regionId',categoryLabel:'regionName',barSeries:['actual'],lineSeries:['budget']};if(kind==='scatter')b.roles={categoryKey:'regionId',categoryLabel:'regionName',x:'budget',y:'actual'};return {data,slide};}
test.each(kinds)('%s compiles SVG and an editable native PPT chart',async kind=>{const {data,slide}=await model(kind);const c=compileSlide(slide,data,'draft');expect(c.diagnostics.filter(d=>d.severity==='error')).toEqual([]);expect(c.elements[0].type).toBe('nativeChart');const svg=renderSlideSvg(c);expect(svg).toContain('<svg');expect(svg).not.toContain('NaN');const dir=await mkdtemp(path.join(tmpdir(),'phase2-'));try{const output=path.join(dir,'chart.pptx');await writePptx(c,output,async()=>{throw new Error('no raster expected')});const zip=await JSZip.loadAsync(await readFile(output));const files=zip.file(/^ppt\/charts\/chart\d+.xml$/);expect(files).toHaveLength(1);const xml=await files[0].async('string');expect(xml).toContain(kind==='combo'?'<c:barChart':kind==='pie'?'<c:pieChart':kind==='donut'?'<c:doughnutChart':kind==='area'?'<c:areaChart':kind==='scatter'?'<c:scatterChart':'<c:barChart');if(kind==='combo')expect(xml).toContain('<c:lineChart');expect(zip.file(/^ppt\/embeddings\/.*\.xlsx$/).length).toBeGreaterThan(0);}finally{await rm(dir,{recursive:true,force:true})}});
test('share charts reject negative or zero totals and refuse multiple measures',async()=>{for(const kind of ['pie','donut','percentStackedColumn']){const {data,slide}=await model(kind);data.resultSets[0].rows[0].actual='-1';expect(compileSlide(slide,data).diagnostics.some(d=>d.code==='INVALID_SHARE_VALUES')).toBe(true)}const {data,slide}=await model('pie');slide.bindings.main.roles.series=['actual','budget'];expect(compileSlide(slide,data).diagnostics.some(d=>d.code==='INVALID_SERIES')).toBe(true)});
test('share chart diagnostics name non-measure fields and prioritize negative values',async()=>{const missing=await model('pie');missing.data.semanticSchema.tables[0].columns.push({id:'sort-order',name:'SortOrder',type:'integer'});missing.data.resultSets[0].fields.push({id:'sort',type:'integer',nullable:false,semanticRef:'sort-order'});missing.data.resultSets[0].rows.forEach((row:any,index:number)=>row.sort=index);missing.slide.bindings.main.roles.series=['sort'];const diagnostic=compileSlide(missing.slide,missing.data).diagnostics.find(d=>d.code==='MISSING_MEASURE');expect(diagnostic?.message).toContain('SortOrder');expect(diagnostic?.message).toContain('不是指标字段');const negative=await model('pie');negative.data.measures.find((measure:any)=>measure.id==='revenue-actual').aggregationBehavior='nonAdditive';negative.data.resultSets[0].rows[0].actual='-1';const diagnostics=compileSlide(negative.slide,negative.data).diagnostics;expect(diagnostics.some(d=>d.code==='INVALID_SHARE_VALUES')).toBe(true);expect(diagnostics.some(d=>d.code==='NON_ADDITIVE_SHARE')).toBe(false)});
test('explicit dual axis preserves distinct units, scatter binds numeric X, and zero/missing data is rejected',async()=>{
 const data=await fixture('phase2-charts.data');const s=createSlide(data,'revenue-margin-combo');
 const dual=compileSlide(s,data,'draft');expect(dual.diagnostics.filter(d=>d.severity==='error')).toEqual([]);const node=dual.elements.find(e=>e.type==='nativeChart')!;expect(node.series![0].values).toEqual([2500,2800,3100]);expect(node.series![1].values).toEqual([18,21,20]);expect(node.valueAxis!.title).toBe('万元');expect(node.secondaryValueAxis.title).toBe('%');
 s.elements.find(e=>e.type==='chart')!.options!.secondaryAxis=false;expect(compileSlide(s,data).diagnostics.some(d=>d.code==='UNIT_MISMATCH')).toBe(true);
 const scatter=createSlide(data,'budget-actual-scatter');const c=compileSlide(scatter,data);const dots=c.elements.find(e=>e.type==='nativeChart')!;expect(dots.xValues).toEqual([1000,900,1100]);expect(dots.series![0].values).toEqual([1200,800,1100]);
 const pie=await model('pie');pie.data.resultSets[0].rows.forEach((r:any)=>r.actual='0');expect(compileSlide(pie.slide,pie.data).diagnostics.some(d=>d.code==='INVALID_SHARE_VALUES')).toBe(true);
 const empty=await model('pie');empty.data.resultSets[0].rows=[];expect(compileSlide(empty.slide,empty.data,'draft').elements[0].text).toBe('无数据');expect(compileSlide(empty.slide,empty.data,'final').diagnostics.some(d=>d.code==='EMPTY_RESULT'&&d.severity==='error')).toBe(true);
 const area=await model('area');area.data.resultSets[1].rows[0].revenue=null;expect(compileSlide(area.slide,area.data).diagnostics.some(d=>d.code==='INCOMPLETE_CHART_DATA')).toBe(true);
});
test('combo labels separate bar tops from line bottoms in SVG and PPT',async()=>{
 const data=await fixture('phase2-charts.data'),c=compileSlide(createSlide(data,'revenue-margin-combo'),data);
 const dir=await mkdtemp(path.join(tmpdir(),'combo-labels-'));
 try{await writePptx(c,path.join(dir,'out.pptx'),async()=>{throw Error('no asset')});const zip=await JSZip.loadAsync(await readFile(path.join(dir,'out.pptx')));const xml=await zip.file(/^ppt\/charts\/chart\d+\.xml$/)[0].async('string');expect(xml).toContain('<c:dLblPos val="b"/>');expect(xml).toContain('<c:dLblPos val="outEnd"/>');}finally{await rm(dir,{recursive:true,force:true})}
});
test('advanced chart styling stays aligned between SVG and editable PPT geometry',async()=>{
 const {data,slide}=await model('stackedColumn');const element=slide.elements[0] as any;element.style={themeId:'teal',seriesColors:['0F766E','F59E0B'],fontSize:14,labelFontSize:12,labelColor:'334155',gridColor:'CBD5E1',barThickness:.9,plotHeight:.7};
 const compiled=compileSlide(slide,data,'draft'),node=compiled.elements[0];expect(node.series?.map(series=>series.color)).toEqual(['0F766E','F59E0B']);expect(node.options).toMatchObject({fontSize:14,labelFontSize:12,barThickness:.9,plotHeight:.7});expect(node.options?.plotAreaLayout.h).toBeLessThan(.7);
 const svg=renderSlideSvg(compiled);expect(svg).toContain('font-size="14"');expect(svg).toContain('stroke="#CBD5E1"');
 const dir=await mkdtemp(path.join(tmpdir(),'phase2-style-'));try{const output=path.join(dir,'styled.pptx');await writePptx(compiled,output,async()=>{throw Error('no asset')});const zip=await JSZip.loadAsync(await readFile(output));const xml=await zip.file(/^ppt\/charts\/chart\d+\.xml$/)[0].async('string');expect(xml).toContain('<c:gapWidth val="50"');expect(xml).toContain('<c:manualLayout>');}finally{await rm(dir,{recursive:true,force:true})}
});
