import {afterAll,expect,test} from 'vitest';
import express from 'express';
import request from 'supertest';
import {Pool} from 'pg';
import {registerFolderRoutes} from '../src/folders.ts';
const pool=new Pool({connectionString:'postgresql://slidebi_app@localhost:5432/slidebi_test'});
afterAll(()=>pool.end());
function appFor(actor:number){const app=express();app.use(express.json());registerFolderRoutes(app,pool,actor);app.use((e:any,_req:any,res:any,_next:any)=>res.status(e.status||500).json({code:e.code,message:e.message}));return app}
test('folder hierarchy is owner-scoped and non-empty folders cannot be removed',async()=>{const users=(await pool.query("SELECT id,username FROM app.users WHERE username IN ('marx','summer')")).rows;const marx=appFor(Number(users.find(u=>u.username==='marx').id)),summer=appFor(Number(users.find(u=>u.username==='summer').id));const parent=await request(marx).post('/api/folders').send({kind:'data',name:'目录测试'});expect(parent.status).toBe(201);const child=await request(marx).post('/api/folders').send({kind:'data',name:'子目录',parentId:parent.body.id});expect(child.status).toBe(201);try{expect((await request(marx).delete(`/api/folders/${parent.body.id}`)).status).toBe(409);expect((await request(summer).patch(`/api/folders/${parent.body.id}`).send({name:'侵入'})).status).toBe(404);expect((await request(summer).get('/api/folders?kind=data')).body.items.some((f:any)=>f.id===parent.body.id)).toBe(false);expect((await request(marx).patch(`/api/folders/${parent.body.id}`).send({name:'经营目录'})).status).toBe(200)}finally{await request(marx).delete(`/api/folders/${child.body.id}`);await request(marx).delete(`/api/folders/${parent.body.id}`)}});
test('template folders support creation and owner navigation',async()=>{const owner=Number((await pool.query("SELECT id FROM app.users WHERE username='marx'")).rows[0].id),app=appFor(owner);const created=await request(app).post('/api/folders').send({kind:'templates',name:'商业汇报'});expect(created.status).toBe(201);try{expect((await request(app).get('/api/folders?kind=templates')).body.items.some((f:any)=>f.id===created.body.id)).toBe(true)}finally{await request(app).delete(`/api/folders/${created.body.id}`)}});
