import type {Express} from 'express';
import type {Pool} from 'pg';
import {type DB,id,hash,fail,transaction,getSlide,getData,insertRevision} from './db.ts';
import {lockDataset,createDataset,storeData} from './datasets.ts';
import {getDeck,saveRevision,validatedSpec} from './decks.ts';
const name=(v:any)=>{if(typeof v!=='string'||!v.trim()||v.trim().length>80)fail(422,'INVALID_TITLE','文稿名称为1至80字');return v.trim();};
const freshSpec=(did:string,title:string)=>({id:did,revision:1,title,sections:[{id:'pages',title:'正文',order:0}],instances:[] as any[],structurePolicy:{cover:false,agenda:false,sectionDividers:false,agendaPageCapacity:8},numbering:{mode:'contentOnly',showTotal:true}});
async function create(db:DB,actor:number,title:string){const spec=freshSpec(id('deck'),name(title));await db.query('INSERT INTO app.decks(id,owner_id,current_revision,native_content) VALUES($1,$2,1,true)',[spec.id,actor]);await saveRevision(db,actor,spec);return spec;}
async function publish(db:DB,actor:number,spec:any){await saveRevision(db,actor,spec);await db.query('UPDATE app.decks SET current_revision=$2,updated_at=now() WHERE id=$1',[spec.id,spec.revision]);}
async function clonePage(db:DB,actor:number,sid:string,did:string,sourceContentId?:string){
 let link=(await db.query('SELECT dataset_id FROM app.slides WHERE id=$1 AND owner_id=$2',[sid,actor])).rows[0];
 if(link?.dataset_id)await lockDataset(db,actor,link.dataset_id);
 const s=await getSlide(db,actor,sid);if(s.archivedAt&&!sourceContentId)fail(422,'SLIDE_ARCHIVED','页面已归档');
 if(!link&&s.extensions?.chartData){const data=await storeData(db,actor,await getData(db,actor,s.snapshotRef));s.snapshotRef=data.snapshot.id;s.reviewState={status:'needsReview',snapshotId:data.snapshot.id};for(const source of Object.values(s.extensions.chartData) as any[]){source.mode='private';delete source.datasetId;delete source.datasetVersion;}link={dataset_id:null};}
 if(!link){const data=await getData(db,actor,s.snapshotRef),dataset=await createDataset(db,actor,{name:s.title,dataSpec:data});link={dataset_id:dataset.id};s.snapshotRef=dataset.currentSnapshotId;s.reviewState={status:'needsReview',snapshotId:s.snapshotRef};}
 const copy=structuredClone(s),mapping=new Map<string,string>();
 for(const e of copy.elements){mapping.set(e.id,id('element'));if(e.groupId&&!mapping.has(e.groupId))mapping.set(e.groupId,id('group'));}
 copy.elements=copy.elements.map((e:any)=>({...e,id:mapping.get(e.id),...(e.groupId?{groupId:mapping.get(e.groupId)}:{})}));
 if(copy.extensions?.chartData)copy.extensions.chartData=Object.fromEntries(Object.entries(copy.extensions.chartData).map(([k,v])=>[mapping.get(k)||k,v]));
 copy.annotations=(copy.annotations||[]).map((a:any)=>({...a,id:id('annotation')}));
 copy.layoutOverrides=Object.fromEntries(Object.entries(copy.layoutOverrides||{}).map(([k,v])=>[mapping.get(k)||k,v]));
 copy.id=id('slide');copy.revision=1;delete copy.archivedAt;copy.extensions={...copy.extensions,importedFrom:{contentId:sourceContentId??null,slideId:sid,revision:s.revision}};
 await db.query('INSERT INTO app.slides(id,owner_id,current_revision,dataset_id,content_deck_id) VALUES($1,$2,1,$3,$4)',[copy.id,actor,link.dataset_id,did]);await insertRevision(db,actor,copy);return copy;
}
async function repairActivePages(db:DB,actor:number,d:any){
 if(!d.canEdit||!d.spec.instances.length)return;
 if(!(await db.query('SELECT native_content FROM app.decks WHERE id=$1 AND owner_id=$2',[d.id,actor])).rows[0]?.native_content)return;
 const ids=d.spec.instances.map((i:any)=>i.slideRef.id);
 await db.query('UPDATE app.slides SET archived_at=NULL WHERE id=ANY($1::text[]) AND owner_id=$2 AND content_deck_id=$3 AND archived_at IS NOT NULL',[ids,actor,d.id]);
}
async function currentNativeInput(db:DB,actor:number,d:any,input:any){
 const next=structuredClone(input),currentIds=new Set(d.spec.instances.map((i:any)=>i.slideRef.id));
 if(!Array.isArray(next?.instances))return next;
 for(const i of next.instances){
  if(!currentIds.has(i?.slideRef?.id))continue;
  const row=(await db.query('SELECT current_revision FROM app.slides WHERE id=$1 AND owner_id=$2 AND content_deck_id=$3 FOR UPDATE',[i.slideRef.id,actor,d.id])).rows[0];
  if(row){await db.query('UPDATE app.slides SET archived_at=NULL WHERE id=$1',[i.slideRef.id]);i.slideRef.revision=row.current_revision;}
 }
 return next;
}
async function detail(db:DB,actor:number,did:string){const d=await getDeck(db,actor,did);await repairActivePages(db,actor,d);const pages=[];const compare=(a:{order:number;id:string},b:{order:number;id:string})=>a.order-b.order||(a.id<b.id?-1:a.id>b.id?1:0);const ordered=[...d.spec.sections].sort(compare).flatMap((section:any)=>d.spec.instances.filter((i:any)=>i.sectionId===section.id).sort((a:any,b:any)=>compare({...a,id:a.instanceId},{...b,id:b.instanceId})));for(const i of ordered){const s=await getSlide(db,actor,i.slideRef.id);pages.push({instanceId:i.instanceId,slideId:s.id,revision:s.revision,title:s.title,sectionId:i.sectionId,order:i.order,included:i.included});}return {...d,pages,pageCount:pages.length};}
async function lock(db:DB,actor:number,did:string,revision:any){if(!(await db.query('SELECT id FROM app.decks WHERE id=$1 AND owner_id=$2 FOR UPDATE',[did,actor])).rowCount)fail(403,'OWNER_REQUIRED','仅 owner 可以修改文稿');const d=await getDeck(db,actor,did);if(!Number.isInteger(revision)||revision!==d.revision)fail(409,'REVISION_CONFLICT','文稿已更新，请重新加载');return d;}
export async function ensureContents(pool:Pool,actor:number){await transaction(pool,async db=>{
 await db.query('SELECT pg_advisory_xact_lock(72638102,$1::int)',[actor]);
 const legacy=(await db.query('SELECT id FROM app.decks WHERE owner_id=$1 AND archived_at IS NULL AND NOT native_content FOR UPDATE',[actor])).rows;
 for(const row of legacy){const d=await getDeck(db,actor,row.id);const spec=structuredClone(d.spec);spec.revision++;for(const i of spec.instances){const copy=await clonePage(db,actor,i.slideRef.id,d.id,d.id);i.slideRef={id:copy.id,revision:1};}await publish(db,actor,spec);await db.query('UPDATE app.decks SET native_content=true WHERE id=$1',[d.id]);}
 const orphans=(await db.query('SELECT s.id FROM app.slides s WHERE s.owner_id=$1 AND s.archived_at IS NULL AND s.content_deck_id IS NULL AND NOT EXISTS(SELECT 1 FROM app.deck_slide_refs r WHERE r.slide_id=s.id) FOR UPDATE',[actor])).rows;
 for(const row of orphans){const s=await getSlide(db,actor,row.id);const did=id('deck'),spec=freshSpec(did,s.title.slice(0,80));spec.instances=[{instanceId:id('instance'),slideRef:{id:s.id,revision:s.revision},sectionId:'pages',order:0,included:true}];await db.query('INSERT INTO app.decks(id,owner_id,current_revision,native_content) VALUES($1,$2,1,true)',[did,actor]);await saveRevision(db,actor,spec);await db.query('UPDATE app.slides SET content_deck_id=$2 WHERE id=$1',[s.id,did]);}
 });}
export function registerContentRoutes(app:Express,pool:Pool,actor:number,key:(req:any)=>string){
 app.get('/api/contents',async(_req,res)=>{await ensureContents(pool,Number(actor));const rows=(await pool.query('SELECT id FROM app.decks WHERE (owner_id=$1 OR visibility=\'public\') AND native_content AND archived_at IS NULL ORDER BY updated_at DESC,id',[Number(actor)])).rows;res.json({items:await Promise.all(rows.map(r=>detail(pool,Number(actor),r.id)))});});
 app.post('/api/contents',async(req,res)=>res.status(201).json(await transaction(pool,async db=>{const s=await create(db,Number(actor),req.body.title);return detail(db,Number(actor),s.id);}))); 
 app.get('/api/contents/:id',async(req,res)=>res.json(await detail(pool,Number(actor),req.params.id)));
 app.put('/api/contents/:id',async(req,res)=>res.json(await transaction(pool,async db=>{const d=await lock(db,Number(actor),req.params.id,req.body.revision);const input=await currentNativeInput(db,Number(actor),d,req.body.spec),spec=await validatedSpec(db,Number(actor),input,d.id,d.revision+1,true);const ids=new Set<string>();for(const i of spec.instances){const own=(await db.query('SELECT content_deck_id FROM app.slides WHERE id=$1 AND owner_id=$2',[i.slideRef.id,Number(actor)])).rows[0];if(own?.content_deck_id!==d.id||ids.has(i.slideRef.id))fail(422,'PAGE_OWNERSHIP','请使用导入功能复制其他文稿页面');ids.add(i.slideRef.id);i.slideRef.revision=(await getSlide(db,Number(actor),i.slideRef.id)).revision;}if(d.spec.instances.some((i:any)=>!ids.has(i.slideRef.id)))fail(422,'USE_REMOVE_PAGE','请使用移除页面功能');await publish(db,Number(actor),spec);return detail(db,Number(actor),d.id);}))); 
 app.post('/api/contents/:id/pages',async(req,res)=>res.status(201).json(await transaction(pool,async db=>{const d=await lock(db,Number(actor),req.params.id,req.body.revision);if(d.spec.instances.length>=100)fail(422,'PAGE_LIMIT','最多100页');const link=(await db.query('SELECT dataset_id FROM app.slides WHERE id=$1 AND owner_id=$2',[req.body.slideId,Number(actor)])).rows[0];if(link?.dataset_id)await lockDataset(db,Number(actor),link.dataset_id);await db.query('SELECT id FROM app.slides WHERE id=$1 AND owner_id=$2 FOR UPDATE',[req.body.slideId,Number(actor)]);const source=await getSlide(db,Number(actor),req.body.slideId);if(source.archivedAt)fail(422,'SLIDE_ARCHIVED','页面已归档');const own=(await db.query('SELECT content_deck_id FROM app.slides WHERE id=$1',[source.id])).rows[0];const s=own.content_deck_id?await clonePage(db,Number(actor),source.id,d.id,own.content_deck_id):source;if(!own.content_deck_id)await db.query('UPDATE app.slides SET content_deck_id=$2 WHERE id=$1',[s.id,d.id]);const spec=structuredClone(d.spec);spec.revision++;spec.instances.push({instanceId:id('instance'),slideRef:{id:s.id,revision:s.revision},sectionId:spec.sections[spec.sections.length-1].id,order:Math.max(-1,...spec.instances.map((i:any)=>i.order))+1,included:true});await publish(db,Number(actor),spec);return detail(db,Number(actor),d.id);}))); 
 app.post('/api/contents/:id/import-pages',async(req,res)=>{const k=key(req),fingerprint=hash({id:req.params.id,...req.body});res.status(201).json(await transaction(pool,async db=>{await db.query('SELECT pg_advisory_xact_lock(72638103,$1::int)',[Number(actor)]);const prior=(await db.query('SELECT * FROM app.content_imports WHERE owner_id=$1 AND idempotency_key=$2',[Number(actor),k])).rows[0];if(prior){if(prior.input_hash!==fingerprint)fail(409,'IDEMPOTENCY_CONFLICT','幂等键输入不同');return prior.response;}const d=await lock(db,Number(actor),req.params.id,req.body.revision),source=await detail(db,Number(actor),req.body.sourceContentId),selected=req.body.instanceIds;if(!Array.isArray(selected)||!selected.length||new Set(selected).size!==selected.length||selected.some((x:any)=>!source.pages.some(p=>p.instanceId===x))||d.spec.instances.length+selected.length>100)fail(422,'INVALID_PAGES','请选择有效页面，文稿最多100页');const spec=structuredClone(d.spec);spec.revision++;for(const iid of selected){const page=source.pages.find(p=>p.instanceId===iid)!;const copy=await clonePage(db,Number(actor),page.slideId,d.id,source.id);spec.instances.push({instanceId:id('instance'),slideRef:{id:copy.id,revision:1},sectionId:spec.sections[spec.sections.length-1].id,order:Math.max(-1,...spec.instances.map((i:any)=>i.order))+1,included:true});}await publish(db,Number(actor),spec);const result=await detail(db,Number(actor),d.id);await db.query('INSERT INTO app.content_imports(owner_id,idempotency_key,input_hash,content_id,response) VALUES($1,$2,$3,$4,$5)',[Number(actor),k,fingerprint,d.id,result]);return result;}));});
 app.post('/api/contents/:id/snapshots',async(req,res)=>res.json(await transaction(pool,async db=>{const d=await lock(db,Number(actor),req.params.id,req.body.revision),spec=structuredClone(d.spec);spec.revision++;for(const instance of spec.instances){const row=(await db.query('SELECT current_revision FROM app.slides WHERE id=$1 AND owner_id=$2 AND content_deck_id=$3 FOR UPDATE',[instance.slideRef.id,Number(actor),d.id])).rows[0];if(!row)fail(422,'PAGE_OWNERSHIP','文稿页面归属无效');const slide=await getSlide(db,Number(actor),instance.slideRef.id);if(slide.reviewState?.status!=='reviewed'){slide.revision=Number(row.current_revision)+1;slide.reviewState={status:'reviewed',snapshotId:slide.snapshotRef};await db.query('UPDATE app.slides SET current_revision=$2,updated_at=now(),archived_at=NULL WHERE id=$1',[slide.id,slide.revision]);await insertRevision(db,Number(actor),slide)}instance.slideRef.revision=slide.revision;}await publish(db,Number(actor),spec);return detail(db,Number(actor),d.id);}))); 
 app.post('/api/contents/:id/pages/:instanceId/remove',async(req,res)=>res.json(await transaction(pool,async db=>{const d=await lock(db,Number(actor),req.params.id,req.body.revision),i=d.spec.instances.find((x:any)=>x.instanceId===req.params.instanceId);if(!i)fail(404,'NOT_FOUND','页面不存在');const spec=structuredClone(d.spec);spec.revision++;spec.instances=spec.instances.filter((x:any)=>x.instanceId!==i.instanceId);await publish(db,Number(actor),spec);await db.query('UPDATE app.slides SET archived_at=now(),updated_at=now() WHERE id=$1 AND content_deck_id=$2',[i.slideRef.id,d.id]);return detail(db,Number(actor),d.id);}))); 
 app.post('/api/contents/:id/archive',async(req,res)=>{await transaction(pool,async db=>{await getDeck(db,Number(actor),req.params.id);await db.query('UPDATE app.decks SET archived_at=now(),updated_at=now() WHERE id=$1 AND owner_id=$2',[req.params.id,Number(actor)]);await db.query('UPDATE app.slides SET archived_at=now(),updated_at=now() WHERE content_deck_id=$1 AND owner_id=$2',[req.params.id,Number(actor)]);});res.json({archived:true});});
}
