import type {Express} from 'express';
import type {Pool} from 'pg';
import {fail,id,transaction} from './db.ts';
export function registerFolderRoutes(app:Express,pool:Pool,actor:number){
 const checkName=(name:any)=>{if(typeof name!=='string'||!name.trim()||name.trim().length>200)fail(422,'INVALID_NAME','目录名称需为1至200字');return name.trim()};
 app.get('/api/folders',async(req,res)=>{if(!['data','assets','templates'].includes(String(req.query.kind)))fail(422,'INVALID_KIND','请选择数据、资源或模板目录');const table=req.query.kind==='data'?'datasets':req.query.kind==='templates'?'templates':'assets';const rows=(await pool.query(`WITH RECURSIVE visible AS (SELECT f.* FROM app.folders f WHERE f.kind=$1 AND (f.owner_id=$2 OR EXISTS(SELECT 1 FROM app.${table} e WHERE e.folder_id=f.id AND e.visibility='public' AND e.archived_at IS NULL)) UNION SELECT f.* FROM app.folders f JOIN visible v ON v.parent_id=f.id) SELECT DISTINCT * FROM visible ORDER BY name`,[req.query.kind,Number(actor)])).rows;res.json({items:rows.map(f=>({id:f.id,name:f.name,parentId:f.parent_id,kind:f.kind,ownerId:f.owner_id,canEdit:Number(f.owner_id)===Number(Number(actor))}))})});
 app.post('/api/folders',async(req,res)=>{const {kind,parentId=null}=req.body,name=checkName(req.body.name);if(!['data','assets','templates'].includes(kind))fail(422,'INVALID_KIND','请选择数据、资源或模板目录');if(parentId&&!(await pool.query('SELECT id FROM app.folders WHERE id=$1 AND owner_id=$2 AND kind=$3',[parentId,Number(actor),kind])).rows.length)fail(404,'NOT_FOUND','上级目录不存在');const fid=id('folder');await pool.query('INSERT INTO app.folders(id,kind,name,owner_id,parent_id) VALUES($1,$2,$3,$4,$5)',[fid,kind,name,Number(actor),parentId]);res.status(201).json({id:fid,name,kind,parentId,canEdit:true})});
 app.patch('/api/folders/:id',async(req,res)=>{const name=checkName(req.body.name);const r=await pool.query('UPDATE app.folders SET name=$3,updated_at=now() WHERE id=$1 AND owner_id=$2 RETURNING id',[req.params.id,Number(actor),name]);if(!r.rows.length)fail(404,'NOT_FOUND','目录不存在');res.json({id:req.params.id,name})});
 app.delete('/api/folders/:id',async(req,res)=>{await transaction(pool,async db=>{const f=(await db.query('SELECT * FROM app.folders WHERE id=$1 AND owner_id=$2 FOR UPDATE',[req.params.id,Number(actor)])).rows[0];if(!f)fail(404,'NOT_FOUND','目录不存在');const table=f.kind==='data'?'datasets':f.kind==='templates'?'templates':'assets';if((await db.query(`SELECT id FROM app.folders WHERE parent_id=$1 UNION ALL SELECT id FROM app.${table} WHERE folder_id=$1 AND archived_at IS NULL LIMIT 1`,[f.id])).rows.length)fail(409,'FOLDER_NOT_EMPTY','请先移出目录中的内容或子目录');await db.query(`UPDATE app.${table} SET folder_id=NULL WHERE folder_id=$1`,[f.id]);await db.query('DELETE FROM app.folders WHERE id=$1',[f.id])});res.json({deleted:true})});
}
