import React, { useEffect, useState } from 'react';
import { Upload, Search, Trash2, Image, Shapes, Smile, Globe, Lock, Folder, FolderCog, Download } from 'lucide-react';
import {api,post} from './api';
import {Modal} from './ui';
import {DirectoryBrowser,InlineName} from './DirectoryBrowser';
import {ImageProcessing} from './ImageProcessing';
import './asset-library.css';
import {useLibraryNavigation,LibraryToolbar} from './LibraryNavigation';
const kinds=[['icon','图标'],['vector','矢量图'],['image','图片']];
function KindIcon({kind}:{kind:string}){const Icon=kind==='icon'?Smile:kind==='vector'?Shapes:Image;return <Icon size={16} aria-label={kinds.find(k=>k[0]===kind)?.[1]||'图片'}/>}
export function AssetLibrary({onSelect,folderId:externalFolder,onFolderChange,toolbar}:{onSelect?:(asset:any)=>void;folderId?:string|null;onFolderChange?:(id:string|null)=>void;toolbar?:React.ReactNode}){
 const[assets,A]=useState<any[]>([]),[localFolder,F]=useState<string|null>(null),[folders,Fs]=useState<any[]>([]),[search,Q]=useState(''),[selected,S]=useState<any>(),[error,E]=useState(''),[busy,B]=useState(false),[confirm,C]=useState<any>(),[uploading,U]=useState(false),[manage,M]=useState(false),[moving,Move]=useState(false),[kind,K]=useState(''),[uploadKind,UK]=useState('image'),[svgName,N]=useState(''),[svgCode,Code]=useState('');
 const navigation=useLibraryNavigation(),managed=navigation.managed&&navigation.kind==='assets'&&!onSelect;
 const folderId=managed?navigation.folderId:externalFolder===undefined?localFolder:externalFolder;const setFolder=managed?navigation.setFolderId:onFolderChange||F;
 const currentFolders=managed?navigation.folders:folders;
 async function load(){try{const r=await api('/assets');A(r.items||[])}catch(e:any){E(e.message)}}
 useEffect(()=>{load();api('/folders?kind=assets').then(r=>Fs(r.items||[])).catch(e=>E(e.message))},[]);
 function open(a:any){S(a);E('');Move(false)}
 async function patch(a:any,body:any){const updated=await api(`/management/assets/${a.id}`,{method:'PATCH',body:JSON.stringify(body)});S({...a,...body,...updated});await load()}
 async function upload(file?:File,name?:string,assetKind=uploadKind){if(!file)return;B(true);E('');try{const body=new FormData();body.append('file',file);body.append('kind',assetKind);if(name)body.append('name',name);const a=await api('/assets',{method:'POST',body});if(folderId)await api(`/management/assets/${a.id}`,{method:'PATCH',body:JSON.stringify({folderId})});await load();U(false);open({...a,folderId});N('');Code('')}catch(e:any){E(e.message)}finally{B(false)}}
 const visible=assets.filter(a=>(a.folderId??null)===folderId&&a.name?.includes(search)&&(!kind||a.kind===kind));
 return <section className="asset-library asset-library-refined">
 {managed?<LibraryToolbar actions={<button title="上传资源" aria-label="上传资源" onClick={()=>U(true)}><Upload size={18}/></button>}><div className="library-filter-buttons"><button className={!kind?'active':''} onClick={()=>K('')}>全部</button>{kinds.map(([id,label])=><button key={id} className={kind===id?'active':''} onClick={()=>K(id)}>{label}</button>)}</div><label className="search"><Search size={16}/><input aria-label="搜索图片" placeholder="在当前目录按名称搜索" value={search} onChange={e=>Q(e.target.value)}/></label></LibraryToolbar>:toolbar||<div className="asset-toolbar"><div className="row"><span>资源库</span><span className="muted">/</span><span>{folders.find(f=>f.id===folderId)?.name||'全部资源'}</span></div><div className="row"><button title="上传资源" aria-label="上传资源" onClick={()=>U(true)}><Upload size={18}/></button><button title="目录管理" aria-label="目录管理" onClick={()=>M(!manage)}><FolderCog size={18}/></button></div></div>}
 {toolbar&&<button className="asset-upload-trigger" title="上传资源" aria-label="上传资源" onClick={()=>U(true)}><Upload size={18}/></button>}
 {manage&&<DirectoryBrowser kind="assets" value={folderId} onChange={id=>{setFolder(id);api("/folders?kind=assets").then(r=>Fs(r.items||[])).catch(e=>E(e.message))}}/>}
 {!managed&&<div className="asset-filterbar"><div className="row"><button className={!kind?'active':''} onClick={()=>K('')}>全部</button>{kinds.map(([id,label])=><button key={id} className={kind===id?'active':''} onClick={()=>K(id)}>{label}</button>)}</div><label className="search"><Search size={16}/><input aria-label="搜索图片" placeholder="在当前目录按名称搜索" value={search} onChange={e=>Q(e.target.value)}/></label></div>}
 {error&&<p className="error" role="alert">{error}</p>}
 <div className="media-grid">{visible.map(a=><article className="media-card" key={a.id}><button className={`media-thumbnail ${a.kind!=='image'?'is-icon':''}`} aria-label={`预览 ${a.name}`} onClick={()=>open(a)}><img src={a.url||`/api/assets/${a.id}/file`} alt={a.name}/></button>{a.canEdit===true&&<button className="asset-delete" title="删除" aria-label={`删除 ${a.name}`} onClick={()=>C(a)}><Trash2 size={17}/></button>}<div className="media-info"><KindIcon kind={a.kind}/><h3><InlineName name={a.name} canEdit={a.canEdit===true} onSave={async name=>{await api(`/management/assets/${a.id}`,{method:'PATCH',body:JSON.stringify({name})});await load()}}/></h3></div>{onSelect&&<button aria-label={`插入 ${a.name}`} onClick={()=>onSelect(a)}>插入页面</button>}</article>)}</div>
 {!visible.length&&<p className="empty">当前目录暂无匹配资源。</p>}
 {uploading&&<Modal title="上传资源" onClose={()=>U(false)}><label className="field">素材分类<select aria-label="上传素材种类" value={uploadKind} onChange={e=>UK(e.target.value)}>{kinds.map(([v,n])=><option key={v} value={v}>{n}</option>)}</select></label><label className="button primary">选择文件<input aria-label="上传素材文件" type="file" hidden disabled={busy} accept={uploadKind==='vector'?'image/svg+xml,.svg':'image/png,image/jpeg,image/svg+xml,.svg'} onChange={e=>{upload(e.target.files?.[0]);e.target.value=''}}/></label><p className="muted">PNG、JPEG、SVG</p><details className="svg-upload" open={uploadKind==='vector'}><summary>输入 SVG 代码</summary><label className="field">SVG 名称<input value={svgName} maxLength={200} onChange={e=>N(e.target.value)}/></label><label className="field">SVG 代码<textarea rows={6} value={svgCode} onChange={e=>Code(e.target.value)}/></label><button disabled={busy||!svgName.trim()||!svgCode.trim()} onClick={()=>upload(new File([svgCode],svgName.trim().replace(/[\\/]/g,'_')+'.svg',{type:'image/svg+xml'}),svgName.trim(),'vector')}>校验并上传 SVG</button></details>{error&&<p role="alert">{error}</p>}</Modal>}
 {selected&&<Modal title={selected.name} header={<div className="asset-detail-meta"><h3><InlineName name={selected.name} canEdit={selected.canEdit===true} onSave={name=>patch(selected,{name})}/></h3><button title={selected.visibility==='public'?'公开':'私有'} aria-label={`可见性：${selected.visibility==='public'?'公开':'私有'}`} disabled={selected.canEdit!==true} onClick={()=>patch(selected,{visibility:selected.visibility==='public'?'private':'public'}).catch(e=>E(e.message))}>{selected.visibility==='public'?<Globe size={18}/>:<Lock size={18}/>}</button><button title="所属目录" aria-label="修改资源目录" disabled={selected.canEdit!==true} onClick={()=>Move(!moving)}><Folder size={18}/>{currentFolders.find(f=>f.id===selected.folderId)?.name||'根目录'}</button><a className="button" title="下载原始素材" aria-label="下载原始素材" href={selected.originalUrl||selected.url||`/api/assets/${selected.id}/file`} download><Download size={18}/></a></div>} wide onClose={()=>S(undefined)}>{moving&&<label className="field">所属目录<select aria-label="所属目录" value={selected.folderId||''} onChange={e=>patch(selected,{folderId:e.target.value||null}).then(()=>Move(false)).catch(e=>E(e.message))}><option value="">根目录</option>{currentFolders.filter(f=>f.canEdit!==false).map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label>}{error&&<p role="alert" className="error">{error}</p>}{selected.canEdit===true?<ImageProcessing key={selected.id} asset={selected} onSaved={a=>{open(a);load()}}/>:<div className="media-large"><img src={selected.url||`/api/assets/${selected.id}/file`} alt={`${selected.name} 预览`}/></div>}{onSelect&&<button className="primary" onClick={()=>{onSelect(selected);S(undefined)}}>插入此素材</button>}</Modal>}
 {confirm&&<Modal title="删除资源" onClose={()=>C(undefined)}><p>确认删除“{confirm.name}”？已有页面仍可使用此素材。</p><div className="row"><button onClick={()=>C(undefined)}>取消</button><button disabled={busy} onClick={async()=>{B(true);try{await post(`/assets/${confirm.id}/archive`);C(undefined);if(selected?.id===confirm.id)S(undefined);await load()}catch(e:any){E(e.message)}finally{B(false)}}}>确认删除</button></div>{error&&<p role="alert">{error}</p>}</Modal>}
 </section>
}
