import React,{useEffect,useRef,useState} from 'react';
import {Check,ChevronRight,Copy,Database,FolderOpen,Replace,Save,Search} from 'lucide-react';
import {api,post} from './api';
import {TemplateDataTable} from './TemplateDataTable';
import {fieldLabel,Modal} from './ui';

export function defaultChartBinding(data:any){
 const table=data.resultSets[0],category=table.fields.find((f:any)=>!['decimal','integer'].includes(f.type)),series=table.fields.filter((f:any)=>['decimal','integer'].includes(f.type));
 if(!category||!series.length)throw new Error('图表需要至少一个分类字段和一个数值字段。');
 return {resultSetId:table.id,roles:{categoryKey:category.id,categoryLabel:category.id,series:series.map((f:any)=>f.id)}};
}

const ROLE_LABELS:Record<string,string>={
 categoryKey:'分类标识',categoryLabel:'分类名称',series:'数值',stepKey:'步骤标识',label:'名称',role:'步骤类型',value:'数值',sort:'顺序',sortOrder:'顺序',x:'X 值',y:'Y 值',size:'大小',columns:'表格列',
 key:'主键',parent:'父节点',parentId:'父节点',title:'标题',subtitle:'补充说明',group:'分组',category:'分类',segment:'细分',owner:'负责人',status:'状态',progress:'进度',output:'产出',comment:'说明',
 amount:'金额',conversion:'转化率',probability:'概率',impact:'影响',start:'开始日期',end:'结束日期',milestone:'里程碑',region:'区域',quadrant:'象限',item:'内容',priority:'优先级',score:'评分',message:'核心信息',evidence:'支撑信息',stage:'阶段',deliverable:'交付物'
};

export function ChartDataPanel({slideId,chartId,source,frozen=false,onChange,onPreview,onReload,flushSlide,registerFlush}:{slideId:string;chartId:string;source:any;frozen?:boolean;onChange:(source:any)=>void;onPreview:(source:any)=>void;onReload:()=>Promise<void>;flushSlide:()=>Promise<any>;registerFlush:(flush:()=>Promise<void>)=>void}){
 const [value,V]=useState<any>(source),[items,I]=useState<any[]>([]),[folders,Folders]=useState<any[]>([]),[choice,C]=useState(''),[name,N]=useState('图表数据'),[dirty,D]=useState(false),[busy,B]=useState(false),[error,E]=useState(''),[target,T]=useState<any>(),[mapping,Map]=useState<any>(),[linked,Linked]=useState<any>(),[bindingDraft,BindingDraft]=useState<any>(source?.binding);
 const [picker,Picker]=useState(false),[folderId,FolderId]=useState<string|null>(null),[search,SearchValue]=useState('');
 const [copyOpen,CopyOpen]=useState(false),[copyFolderId,CopyFolderId]=useState<string|null>(null);
 const latest=useRef(value);latest.current=value;const pending=useRef(false);pending.current=dirty;const sourceKey=JSON.stringify(source);
 useEffect(()=>{let live=true;if(source?.mode==='private'){V(source);D(false)}else {V(undefined);api(`/slides/${slideId}/chart-data/${chartId}`).then(s=>{if(live){V(s);D(false)}}).catch(e=>{if(live)E(e.message)})};Promise.all([api('/datasets?view=chart'),api('/folders?kind=data')]).then(([datasets,dirs])=>{if(live){I(datasets.items||[]);Folders(dirs.items||[])}}).catch(e=>{if(live)E(e.message)});return()=>{live=false}},[slideId,chartId,sourceKey]);
 useEffect(()=>{BindingDraft(value?.binding)},[JSON.stringify(value?.binding)]);
 useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(pending.current){e.preventDefault();e.returnValue=''}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn)},[]);
 useEffect(()=>{let live=true;if(value?.mode!=='dataset'){Linked(undefined);return}api(`/datasets/${value.datasetId}`).then(d=>{if(live)Linked(d)}).catch(()=>{if(live)Linked({id:value.datasetId,name:value.datasetId})});return()=>{live=false}},[value?.mode,value?.datasetId]);

 async function save(){if(!pending.current||latest.current?.mode!=='dataset')return;B(true);E('');try{await flushSlide();const v=latest.current;const current=await api(`/datasets/${v.datasetId}`);await api(`/datasets/${v.datasetId}`,{method:'PUT',headers:{'If-Match':String(v.datasetVersion)},body:JSON.stringify({name:current.name,dataSpec:v.dataSpec,tags:current.tags,refreshConfig:current.refreshConfig})});D(false);pending.current=false;await onReload();const fresh=await api(`/slides/${slideId}/chart-data/${chartId}`);V(fresh)}catch(e:any){E(e.message);throw e}finally{B(false)}}
 useEffect(()=>{registerFlush(save);return()=>registerFlush(async()=>{})},[dirty,value]);
 async function bind(datasetId:string,bindingOverride?:any){B(true);E('');try{await save();const saved=await flushSlide();await api(`/slides/${slideId}/chart-data/${chartId}`,{method:'PUT',headers:{'If-Match':String(saved.revision)},body:JSON.stringify({mode:'dataset',datasetId,binding:bindingOverride||mapping||value.binding})});await onReload();const fresh=await api(`/slides/${slideId}/chart-data/${chartId}`);V(fresh);D(false);Picker(false);return true}catch(e:any){E(e.message);return false}finally{B(false)}}
 const editable=!frozen&&value?.mode==='dataset'&&value?.canEdit!==false;
 async function selectDataset(datasetId:string){C(datasetId);T(undefined);Map(undefined);if(!datasetId)return;try{const d=await api(`/datasets/${datasetId}`);T(d);const old=value.binding,table=d.dataSpec.resultSets.find((r:any)=>r.id===old.resultSetId)||d.dataSpec.resultSets[0];Map({...old,resultSetId:table.id,roles:Object.fromEntries(Object.entries(old.roles||{}).map(([role,fields]:any)=>[role,Array.isArray(fields)?fields.map((f:string)=>table.fields.some((x:any)=>x.id===f)?f:''):table.fields.some((x:any)=>x.id===fields)?fields:'']))})}catch(e:any){E(e.message)}}
 const validMapping=mapping&&Object.values(mapping.roles||{}).every((v:any)=>Array.isArray(v)?v.length&&v.every(Boolean):!!v);
 const activeResult=value?.dataSpec?.resultSets?.find((result:any)=>result.id===bindingDraft?.resultSetId)??value?.dataSpec?.resultSets?.[0];
 const bindingChanged=!!value&&!!bindingDraft&&JSON.stringify(bindingDraft)!==JSON.stringify(value.binding);
 const validBinding=bindingDraft&&Object.values(bindingDraft.roles||{}).every((entry:any)=>Array.isArray(entry)?entry.length>0&&entry.length<=8&&entry.every(Boolean):!!entry);
 async function applyBinding(){if(!bindingChanged||!validBinding)return;if(value.mode==='dataset')await bind(value.datasetId,bindingDraft);else{const next={...value,binding:bindingDraft};V(next);onChange(next)}}
 const chartDataSpec=value?.dataSpec?{...value.dataSpec,resultSets:value.dataSpec.resultSets.filter((result:any)=>result.id===value.binding?.resultSetId)}:undefined;
 const chartResults=chartDataSpec?.resultSets.length?chartDataSpec.resultSets:value?.dataSpec?.resultSets||[];
 function change(next:any){V(next);if(next.mode==='dataset'){D(true);onPreview(next)}else onChange(next)}
 const descendants=(parent:string|null)=>{if(parent===null)return new Set(folders.map(folder=>folder.id));const ids=new Set<string>([parent]);let changed=true;while(changed){changed=false;for(const folder of folders)if(ids.has(folder.parentId)&&!ids.has(folder.id)){ids.add(folder.id);changed=true}}return ids};
 const scope=descendants(folderId),visibleItems=items.filter(item=>{const matches=!search.trim()||String(item.name||'').toLowerCase().includes(search.trim().toLowerCase());return matches&&(folderId===null||scope.has(item.folderId))});
 const folderTree=(parent:string|null):React.ReactNode=><ul>{folders.filter(folder=>(folder.parentId??null)===parent).map(folder=><li key={folder.id}><button type="button" className={folderId===folder.id?'active':''} aria-label={`打开目录 ${folder.name}`} onClick={()=>FolderId(folder.id)}><ChevronRight size={14}/><span>{folder.name}</span></button>{folderTree(folder.id)}</li>)}</ul>;
 const copyTree=(parent:string|null):React.ReactNode=><ul>{folders.filter(folder=>(folder.parentId??null)===parent).map(folder=><li key={folder.id}><button type="button" className={copyFolderId===folder.id?'active':''} aria-label={`选择托管目录 ${folder.name}`} onClick={()=>CopyFolderId(folder.id)}><ChevronRight size={14}/><span>{folder.name}</span></button>{copyTree(folder.id)}</li>)}</ul>;
 async function copyToManagement(){if(!name.trim())return;B(true);E('');try{const d=await post('/datasets',{name:name.trim(),dataSpec:chartDataSpec,preserveResultSets:true,tags:{用途:['页面数据']}});if(copyFolderId)await api(`/management/data/${d.id}`,{method:'PATCH',body:JSON.stringify({folderId:copyFolderId})});if(await bind(d.id,value.binding))CopyOpen(false)}catch(e:any){E(e.message)}finally{B(false)}}

 return <section className="chart-data-panel" aria-label="图表数据"><h3>图表数据</h3>{error&&<p role="alert" className="error">{error}</p>}{value&&<>
  <div className="data-binding-row">{value.mode==='dataset'?<a className="data-binding-note data-binding-link" aria-label={`打开数据集 ${linked?.name||value.datasetId}`} href={`/data?dataset=${encodeURIComponent(value.datasetId)}`}><Database size={15}/><span>已绑定：{linked?.name||value.datasetId}</span></a>:<p className="data-binding-note">未绑定数据管理</p>}{!frozen&&<button type="button" className="icon-button" title={value.mode==='dataset'?'重新绑定数据集':'绑定数据集'} aria-label={value.mode==='dataset'?'重新绑定数据集':'绑定数据集'} onClick={()=>{Picker(true);C('');T(undefined);Map(undefined)}}><Replace size={16}/></button>}</div>
  {value.mode==='dataset'&&value.canEdit===false&&<p className="muted">此数据仅可查看，可另存一份后编辑。</p>}
  <section className="current-binding" aria-label="字段配置"><h4>字段配置</h4>
   {Array.isArray(bindingDraft?.roles?.columns)?<fieldset disabled={frozen||busy}><legend>表格字段（1–8个）</legend><div className="compact-column-fields">{activeResult?.fields.map((field:any)=><label className="check" key={field.id}><input type="checkbox" checked={bindingDraft.roles.columns.includes(field.id)} disabled={!bindingDraft.roles.columns.includes(field.id)&&bindingDraft.roles.columns.length>=8} onChange={event=>BindingDraft({...bindingDraft,roles:{...bindingDraft.roles,columns:event.target.checked?[...bindingDraft.roles.columns,field.id]:bindingDraft.roles.columns.filter((id:string)=>id!==field.id)}})}/>{fieldLabel(value.dataSpec,field)}</label>)}</div></fieldset>:<div className="chart-binding-fields current-role-fields">{Object.entries(bindingDraft?.roles||{}).flatMap(([role,entry]:any)=>(Array.isArray(entry)?entry:[entry]).map((fieldId:string,index:number)=><label className="field compact-role-field" key={`${role}-${index}`}><span>{ROLE_LABELS[role]||role}{Array.isArray(entry)?` ${index+1}`:''}</span><select aria-label={`当前绑定 ${role} ${index+1}`} value={fieldId} disabled={frozen||busy} onChange={event=>BindingDraft({...bindingDraft,roles:{...bindingDraft.roles,[role]:Array.isArray(entry)?entry.map((id:string,i:number)=>i===index?event.target.value:id):event.target.value}})}>{activeResult?.fields.map((field:any)=><option key={field.id} value={field.id}>{fieldLabel(value.dataSpec,field)}</option>)}</select></label>))}</div>}
   {!frozen&&<button type="button" disabled={!bindingChanged||!validBinding||busy} onClick={()=>applyBinding().catch((e:any)=>E(e.message))}><Save size={15}/>应用字段配置</button>}
  </section>
  {chartResults.map((rs:any)=><TemplateDataTable key={rs.id} result={rs} dataSpec={value.dataSpec} editable={editable&&!busy} onChange={updated=>change({...value,dataSpec:{...value.dataSpec,resultSets:value.dataSpec.resultSets.map((t:any)=>t.id===updated.id?updated:t)}})}/>)}
  {value.mode==='dataset'&&editable&&<button disabled={!dirty||busy} onClick={()=>save().catch(()=>{})}><Save size={15}/>保存共享数据</button>}
  {!frozen&&value.mode==='private'&&<button aria-label="copy到数据管理" disabled={busy} onClick={()=>{N('图表数据');CopyFolderId(null);CopyOpen(true)}}><Copy size={15}/>copy到数据管理</button>}
 </>}{!value&&<p>正在读取图表数据…</p>}
 {!frozen&&picker&&<Modal title={value?.mode==='dataset'?'重新绑定数据集':'绑定数据集'} wide onClose={()=>Picker(false)}><div className="dataset-picker-search"><Search size={16}/><input autoFocus aria-label="搜索可见数据集" placeholder="数据集名称" value={search} onChange={e=>SearchValue(e.target.value)}/></div><div className="dataset-picker-layout"><nav className="dataset-picker-tree" aria-label="数据集目录树"><button type="button" className={folderId===null?'active':''} onClick={()=>FolderId(null)}><FolderOpen size={15}/>全部数据</button>{folderTree(null)}</nav><section className="dataset-picker-results" aria-label="可见数据集">{visibleItems.map(item=><button type="button" key={item.id} className={choice===item.id?'selected':''} aria-label={`选择数据集 ${item.name}`} onClick={()=>selectDataset(item.id)}><Database size={16}/><span>{item.name}</span></button>)}{!visibleItems.length&&<p className="muted">没有匹配的可见数据集</p>}</section></div>{target&&mapping&&<div className="chart-binding-fields"><label className="field">数据表<select value={mapping.resultSetId} onChange={e=>Map({...mapping,resultSetId:e.target.value,roles:Object.fromEntries(Object.entries(mapping.roles||{}).map(([k,v])=>[k,Array.isArray(v)?v.map(()=>''):'']))})}>{target.dataSpec.resultSets.map((r:any)=><option key={r.id} value={r.id}>{r.name||r.id}</option>)}</select></label>{Object.entries(mapping.roles||{}).flatMap(([role,v]:any)=>(Array.isArray(v)?v:[v]).map((field:string,index:number)=><label className="field" key={`${role}-${index}`}>{ROLE_LABELS[role]||role}{Array.isArray(v)?` ${index+1}`:''}<select aria-label={`绑定 ${role} ${index+1}`} value={field} onChange={e=>Map({...mapping,roles:{...mapping.roles,[role]:Array.isArray(v)?v.map((x:string,i:number)=>i===index?e.target.value:x):e.target.value}})}><option value="">选择字段</option>{target.dataSpec.resultSets.find((r:any)=>r.id===mapping.resultSetId)?.fields.map((f:any)=><option key={f.id} value={f.id}>{f.name||f.id}</option>)}</select></label>))}</div>}<footer><button type="button" onClick={()=>Picker(false)}>取消</button><button type="button" className="primary" disabled={!choice||busy||!validMapping} onClick={()=>bind(choice,mapping)}><Check size={15}/>{value?.mode==='dataset'?'确认重新绑定':'确认绑定'}</button></footer></Modal>}
 {!frozen&&copyOpen&&<Modal title="copy到数据管理" onClose={()=>CopyOpen(false)}><label className="field">数据集名称<input autoFocus aria-label="数据集名称" value={name} onChange={event=>N(event.target.value)}/></label><p className="muted">选择托管目录</p><nav className="dataset-picker-tree copy-folder-tree" aria-label="托管目录树"><button type="button" className={copyFolderId===null?'active':''} aria-label="选择托管目录 根目录" onClick={()=>CopyFolderId(null)}><FolderOpen size={15}/>根目录</button>{copyTree(null)}</nav><footer><button type="button" onClick={()=>CopyOpen(false)}>取消</button><button type="button" className="primary" disabled={busy||!name.trim()} onClick={()=>copyToManagement()}><Check size={15}/>确认copy并绑定</button></footer></Modal>}
 </section>;
}
