// @vitest-environment jsdom
import React from 'react';
import {render,screen,fireEvent,cleanup,waitFor,act} from '@testing-library/react';
import {afterEach,it,expect,vi} from 'vitest';
import {ChartDataPanel,defaultChartBinding} from './ChartDataPanel';
import {toDataSpec,tableSample} from './table-import';
import {api,post} from './api';
vi.mock('./api',()=>({api:vi.fn(),post:vi.fn()}));
afterEach(()=>{cleanup();vi.clearAllMocks()});
const data=toDataSpec(tableSample);const privateSource={mode:'private',dataSpec:data,binding:defaultChartBinding(data)};
function props(source:any=privateSource){return {slideId:'s',chartId:'c',source,onChange:vi.fn(),onPreview:vi.fn(),onReload:vi.fn(async()=>{}),flushSlide:vi.fn(async()=>({revision:7})),registerFlush:vi.fn()}}
it('copies only the bound table into a chosen data directory before editing',async()=>{const extra={...data.resultSets[0],id:'unused',name:'无关数据表'},source={...privateSource,dataSpec:{...data,resultSets:[data.resultSets[0],extra]}};const managed={...privateSource,mode:'dataset',datasetId:'copied',datasetVersion:1,canEdit:true};vi.mocked(api).mockImplementation(async(path,init)=>path==='/datasets?view=chart'?{items:[]}:path==='/folders?kind=data'?{items:[{id:'quarter',name:'季度数据',parentId:null}]}:path==='/management/data/copied'&&init?.method==='PATCH'?{}:path==='/slides/s/chart-data/c'&&init?.method==='PUT'?{}:path==='/slides/s/chart-data/c'?managed:{name:'图表数据',tags:{用途:['页面数据']},refreshConfig:{mode:'manual'}});vi.mocked(post).mockResolvedValue({id:'copied'});const p=props(source);render(<ChartDataPanel {...p}/>);await screen.findByText('未绑定数据管理');expect(screen.queryByLabelText('table 第1行 实际收入')).toBeNull();expect(screen.queryByText('无关数据表')).toBeNull();fireEvent.click(screen.getByRole('button',{name:'copy到数据管理'}));const dialog=await screen.findByRole('dialog',{name:'copy到数据管理'});fireEvent.change(screen.getByRole('textbox',{name:'数据集名称'}),{target:{value:'图表托管数据'}});fireEvent.click(screen.getByRole('button',{name:'选择托管目录 季度数据'}));fireEvent.click(screen.getByRole('button',{name:'确认copy并绑定'}));await waitFor(()=>expect(post).toHaveBeenCalled());const create=vi.mocked(post).mock.calls[0][1];expect(create.name).toBe('图表托管数据');expect(create.dataSpec.resultSets.map((result:any)=>result.id)).toEqual(['table']);expect(api).toHaveBeenCalledWith('/management/data/copied',expect.objectContaining({method:'PATCH',body:JSON.stringify({folderId:'quarter'})}));expect(api).toHaveBeenCalledWith('/slides/s/chart-data/c',expect.objectContaining({method:'PUT',headers:{'If-Match':'7'}}));expect(p.onReload).toHaveBeenCalled();await screen.findByLabelText('table 第1行 实际收入');expect(document.body.contains(dialog)).toBe(false)});
it('uses server permissions for managed chart data even when the extension claims editable',async()=>{vi.mocked(api).mockImplementation(async(path)=>path==='/datasets?view=chart'?{items:[]}:{...privateSource,mode:'dataset',datasetId:'d',datasetVersion:1,canEdit:false});render(<ChartDataPanel {...props({...privateSource,mode:'dataset',datasetId:'d',canEdit:true})}/>);await screen.findByText('此数据仅可查看，可另存一份后编辑。');expect(screen.queryByLabelText('table 第1行 实际收入')).toBeNull();expect(screen.queryByText('保存共享数据')).toBeNull()});
it('flushes managed edits with the dataset version and keeps dirty values when save fails',async()=>{const managed={...privateSource,mode:'dataset',datasetId:'d',datasetVersion:3,canEdit:true};vi.mocked(api).mockImplementation(async(path,init)=>{if(init?.method==='PUT')throw new Error('保存失败测试');return path==='/datasets?view=chart'?{items:[]}:path==='/datasets/d'?{name:'共享数据',tags:{},refreshConfig:{mode:'manual'}}:managed});const p=props(managed);let flush:any;p.registerFlush=vi.fn(fn=>{flush=fn});render(<ChartDataPanel {...p}/>);const cell=await screen.findByLabelText('table 第1行 实际收入');fireEvent.change(cell,{target:{value:'250'}});fireEvent.blur(cell);await act(async()=>{await expect(flush()).rejects.toThrow('保存失败测试')});expect(p.flushSlide).toHaveBeenCalled();expect(api).toHaveBeenCalledWith('/datasets/d',expect.objectContaining({method:'PUT',headers:{'If-Match':'3'}}));expect((screen.getByLabelText('table 第1行 实际收入') as HTMLInputElement).value).toBe('250');expect(p.onReload).not.toHaveBeenCalled()});
it('rebinds through a searchable directory picker only after explicit confirmation',async()=>{const binding={resultSetId:'table',roles:{stepKey:'f1',label:'f1',role:'f1',value:'f2',sort:'f3'}},managed={...privateSource,mode:'dataset',datasetId:'old',datasetVersion:1,canEdit:true,binding};vi.mocked(api).mockImplementation(async(path,init)=>path==='/datasets?view=chart'?{items:[{id:'d',name:'瀑布数据',folderId:'quarter'}]}:path==='/folders?kind=data'?{items:[{id:'quarter',name:'季度',parentId:null}]}:path==='/datasets/d'?{id:'d',name:'瀑布数据',dataSpec:data}:path==='/datasets/old'?{id:'old',name:'旧数据'}:path==='/slides/s/chart-data/c'&&init?.method==='PUT'?{}:managed);const p=props(managed);render(<ChartDataPanel {...p}/>);fireEvent.click(await screen.findByRole('button',{name:'重新绑定数据集'}));expect(screen.getByRole('dialog',{name:'重新绑定数据集'})).toBeTruthy();expect(screen.getByRole('button',{name:'打开目录 季度'})).toBeTruthy();fireEvent.click(screen.getByRole('button',{name:'打开目录 季度'}));fireEvent.change(screen.getByLabelText('搜索可见数据集'),{target:{value:'瀑布'}});fireEvent.click(screen.getByRole('button',{name:'选择数据集 瀑布数据'}));await screen.findByLabelText('绑定 stepKey 1');expect(screen.getByLabelText('绑定 role 1')).toBeTruthy();expect(screen.getByLabelText('绑定 value 1')).toBeTruthy();expect(screen.queryByLabelText('绑定 series 1')).toBeNull();fireEvent.click(screen.getByRole('button',{name:'确认重新绑定'}));await waitFor(()=>expect(api).toHaveBeenCalledWith('/slides/s/chart-data/c',expect.objectContaining({method:'PUT',body:expect.stringContaining('"datasetId":"d"')})));expect(p.onReload).toHaveBeenCalled()});
it('shows a managed dataset as a direct link and a rebind action with a hover hint',async()=>{const managed={...privateSource,mode:'dataset',datasetId:'d',datasetVersion:1,canEdit:true};vi.mocked(api).mockImplementation(async(path)=>path==='/datasets?view=chart'?{items:[]}:path==='/folders?kind=data'?{items:[]}:path==='/datasets/d'?{id:'d',name:'华东收入'}:managed);render(<ChartDataPanel {...props(managed)}/>);const link=await screen.findByRole('link',{name:'打开数据集 华东收入'});expect(link.getAttribute('href')).toBe('/data?dataset=d');const modify=screen.getByRole('button',{name:'重新绑定数据集'});expect(modify.getAttribute('title')).toBe('重新绑定数据集');expect(modify.querySelector('.lucide-replace')).toBeTruthy();expect(screen.queryByText('已关联数据管理；修改将同步所有引用图表。')).toBeNull();});
it('keeps table columns in the data tab and applies them by stable field id',async()=>{const tableSource={...privateSource,binding:{resultSetId:'table',roles:{columns:['f1','f2']}}},p=props(tableSource);vi.mocked(api).mockImplementation(async(path)=>path==='/datasets?view=chart'?{items:[]}:path==='/folders?kind=data'?{items:[]}:tableSource);render(<ChartDataPanel {...p}/>);const config=await screen.findByRole('region',{name:'字段配置'});expect(config.textContent).toContain('月份');expect(config.textContent).toContain('实际收入');const actual=screen.getByRole('checkbox',{name:'实际收入'});fireEvent.click(actual);fireEvent.click(screen.getByRole('button',{name:'应用字段配置'}));expect(p.onChange).toHaveBeenCalledWith(expect.objectContaining({binding:{resultSetId:'table',roles:{columns:['f1']}}}))});
it('lays out chart role selectors as compact rows',async()=>{vi.mocked(api).mockImplementation(async(path)=>path==='/datasets?view=chart'?{items:[]}:path==='/folders?kind=data'?{items:[]}:privateSource);render(<ChartDataPanel {...props()}/>);const config=await screen.findByRole('region',{name:'字段配置'});const fields=Array.from(config.querySelectorAll('label.compact-role-field'));expect(fields.length).toBeGreaterThan(0);expect(fields.every(field=>field.querySelector('select'))).toBe(true)});
