import React,{useCallback,useEffect,useRef,useState} from 'react';
import {compileSlide,renderSlideSvg} from '@slidebi/presentation';
import {api,post,Template} from './api';
import {Editor} from './Editor';
import {AddPageDialog} from './AddPageDialog';
import {Modal} from './ui';
import {downloadPptxExport} from './export-download';
import './content.css';
import {Eye,FileDown,Trash2,Globe,LockKeyhole,Plus,Save,ArrowLeft,Settings2,Copy,Maximize2,Minimize2} from 'lucide-react';
export function ContentWorkspace({templates,onExports,initialId,registerLeave}:{templates:Template[];onExports:()=>void;initialId?:string;registerLeave?:(fn:()=>Promise<void>)=>void}) {
 const [items,Items]=useState<any[]>([]),[content,C]=useState<any>(),[slide,S]=useState<any>(),[active,A]=useState(''),[error,E]=useState(''),[busy,B]=useState(false),[wizard,W]=useState(false),[importing,I]=useState(false),[source,Source]=useState<any>(),[selected,Selected]=useState<string[]>([]),[preview,P]=useState<any>(),[previewPage,PP]=useState(0),[mode,M]=useState('final');
 const [settings,Settings]=useState(false);
 const [previewFullscreen,PreviewFullscreen]=useState(false);
 const [editorEpoch,EditorEpoch]=useState(0);
 const [exporting,Exporting]=useState(false);
 const [search,Q]=useState(''),[renaming,N]=useState<string>(),[renameText,RT]=useState('');
 const editable=content?.canEdit!==false;
 const specDraft=useRef<any>(null),running=useRef(false);
 const flushRef=useRef<()=>Promise<any>>(async()=>{}),contentRef=useRef<any>(null);contentRef.current=content;
 const registerFlush=useCallback((fn:()=>Promise<any>)=>{flushRef.current=fn;},[]);
 async function run(fn:()=>Promise<void>){if(running.current)return;running.current=true;B(true);E('');try{await fn();}catch(e:any){E(e.message);}finally{running.current=false;B(false);}}
 async function list(){Items((await api('/contents')).items);}
 async function flush(){if(contentRef.current?.canEdit===false)return;if(slide)await flushRef.current();await flushSpec();}
 async function flushSpec(){if(specDraft.current){const d=contentRef.current;const saved=await api(`/contents/${d.id}`,{method:'PUT',body:JSON.stringify({revision:d.revision,spec:specDraft.current})});specDraft.current=null;contentRef.current=saved;C(saved);}}
 async function saveSnapshot(){await flush();const latest=await api(`/contents/${contentRef.current.id}`),saved=await post(`/contents/${latest.id}/snapshots`,{revision:latest.revision});contentRef.current=saved;C(saved);const page=saved.pages.find((p:any)=>p.instanceId===active)||saved.pages[0];if(page){S(await api(`/slides/${page.slideId}`));A(page.instanceId)}EditorEpoch(value=>value+1);P(undefined);}
 function draftSpec(fn:(s:any)=>void){const s=structuredClone(specDraft.current||contentRef.current.spec);fn(s);specDraft.current=s;C({...contentRef.current,spec:s,pages:contentRef.current.pages.map((p:any)=>{const instance=s.instances.find((x:any)=>x.instanceId===p.instanceId);return instance?{...p,sectionId:instance.sectionId,order:instance.order}:p;})});P(undefined);}
 useEffect(()=>{const guard=(e:BeforeUnloadEvent)=>{if(specDraft.current){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',guard);return()=>window.removeEventListener('beforeunload',guard);},[]);
 useEffect(()=>{registerLeave?.(flush);},[slide,registerLeave]);
 async function select(id:string){await flush();const p=await api(`/slides/${id}`);S(p);A(contentRef.current.pages.find((x:any)=>x.slideId===id)?.instanceId||'');P(undefined);}
 async function load(id:string,keep?:string){const d=await api(`/contents/${id}`);specDraft.current=null;contentRef.current=d;C(d);history.replaceState({},'',`/contents/${id}`);const p=d.pages.find((x:any)=>x.instanceId===keep)||d.pages[0];if(p){S(await api(`/slides/${p.slideId}`));A(p.instanceId);}else{S(undefined);A('');}P(undefined);}
 useEffect(()=>{run(async()=>{await list();const id=initialId||location.pathname.match(/^\/(?:contents|decks)\/([^/]+)$/)?.[1];if(id)await load(id);});},[initialId]);
 async function mutate(path:string,body:any={}){await flush();const d=await post(`/contents/${content.id}${path}`,{revision:contentRef.current.revision,...body});C(d);await load(d.id,active);}
 async function changeSpec(fn:(s:any)=>void){await flush();const spec=structuredClone(contentRef.current.spec);fn(spec);const d=await api(`/contents/${content.id}`,{method:'PUT',body:JSON.stringify({revision:contentRef.current.revision,spec})});contentRef.current=d;C(d);P(undefined);}
 async function preflight(){await flush();const d=await api(`/contents/${content.id}`);contentRef.current=d;C(d);const result=await post(`/decks/${d.id}/preview`,{revision:d.revision,dataPolicy:d.canEdit===false?'snapshot':'latestRequired',deliveryMode:d.canEdit===false?'draft':mode});return {d,result};}
 async function previewDocument(){const {result}=await preflight();P(result);PP(0);PreviewFullscreen(false);}
 async function exportDocument(){Exporting(true);try{const {d,result}=await preflight();const errors=result.diagnostics?.filter((item:any)=>item.severity==='error')||[];if(errors.length)throw new Error(errors.map((item:any)=>item.message||item.code).join('；'));const job=await post(`/decks/${d.id}/export`,{revision:d.revision,previewId:result.previewId,deliveryMode:d.canEdit===false?'draft':mode});await downloadPptxExport(job,d.spec.title||d.title||'Slide Report 文稿');onExports();}finally{Exporting(false);}}
 const pages=[...(content?.pages||[])].sort((a:any,b:any)=>{const sections=content.spec.sections;const delta=(sections.find((s:any)=>s.id===a.sectionId)?.order??0)-(sections.find((s:any)=>s.id===b.sectionId)?.order??0);return delta||a.order-b.order||a.instanceId.localeCompare(b.instanceId);});
 async function reorder(from:number,to:number){if(from===to||to<0||to>=pages.length)return;await changeSpec(s=>{const next=[...pages];const [moved]=next.splice(from,1);next.splice(to,0,moved);next.forEach((x,i)=>{const inst=s.instances.find((z:any)=>z.instanceId===x.instanceId);inst.order=i;inst.sectionId=pages[i].sectionId;});});}
 return <section className="content-workspace" aria-label="我的文稿">{error&&<div role="alert" className="error">{error}</div>}{!content?<><div className="content-list-toolbar"><input aria-label="文稿名称" value={search} onChange={e=>Q(e.target.value)} placeholder="文稿名称"/><button className="primary" title="新建文稿" aria-label="新建文稿" disabled={busy} onClick={()=>run(async()=>{const d=await post('/contents',{title:'未命名文稿'});await load(d.id);W(true);})}><Plus size={19}/></button></div><div className="slide-grid content-gallery">{items.filter(d=>(d.title||d.spec?.title||'').toLowerCase().includes(search.trim().toLowerCase())).map(d=><article className="slide-card" key={d.id}><div className="content-card-heading">{renaming===d.id?<input aria-label="修改文稿名称" autoFocus value={renameText} onChange={e=>RT(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')e.currentTarget.blur();if(e.key==='Escape')N(undefined)}} onBlur={()=>run(async()=>{if(renameText.trim())await api(`/management/contents/${d.id}`,{method:'PATCH',body:JSON.stringify({name:renameText})});N(undefined);await list()})}/>:<button className="content-card-title" aria-label={`打开文稿 ${d.title||d.spec?.title}`} onClick={()=>run(()=>load(d.id))}>{d.title||d.spec?.title}</button>}<span className="content-card-count">{d.pageCount??d.spec?.instances?.length??0} 页</span><time title="最后更新时间" dateTime={d.updatedAt}>{d.updatedAt?new Date(d.updatedAt).toLocaleString('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}):'—'}</time><button disabled={!d.canEdit||busy} title={d.visibility==='public'?'公开':'私有'} aria-label={`${d.title||d.spec?.title} · ${d.visibility==='public'?'公开，点击设为私有':'私有，点击设为公开'}`} onClick={()=>run(async()=>{await api(`/management/contents/${d.id}`,{method:'PATCH',body:JSON.stringify({visibility:d.visibility==='public'?'private':'public'})});await list()})}>{d.visibility==='public'?<Globe size={16}/>:<LockKeyhole size={16}/>}</button>{d.canDelete!==false&&<button title="删除" aria-label={`删除 ${d.title||d.spec?.title}`} onClick={()=>{if(window.confirm(`确定删除文稿「${d.title||d.spec?.title}」？`))run(async()=>{await post(`/contents/${d.id}/archive`);await list()})}}><Trash2 size={16}/></button>}</div><button className="content-card-preview" aria-label={`打开 ${d.title||d.spec?.title} 缩略图`} onClick={()=>run(()=>load(d.id))}>{d.pages?.[0]?<PageThumbnail slideId={d.pages[0].slideId} revision={d.pages[0].revision}/>:<div className="content-empty-thumbnail">空白文稿</div>}</button></article>)}</div></>:<>
 <header className="content-header" aria-label="文稿工具栏"><button title="返回文稿列表" aria-label="文稿列表" disabled={busy} onClick={()=>run(async()=>{await flush();C(undefined);S(undefined);history.pushState({},'','/contents');await list();})}><ArrowLeft size={17}/></button>{editable?<input aria-label="文稿标题" value={content.spec.title} maxLength={80} onChange={e=>draftSpec(s=>{s.title=e.target.value;})}/>:<strong>{content.spec.title}</strong>}{editable&&<><button aria-label="保存文稿" title="保存文稿快照" disabled={busy} onClick={()=>run(saveSnapshot)}><Save size={17}/>保存</button><button aria-label="新增页面" disabled={busy} onClick={()=>run(async()=>{await flush();W(true);})}><Plus size={17}/>新增页面</button><button aria-label="导航与交付设置" disabled={busy} onClick={()=>Settings(true)}><Settings2 size={17}/>导航与交付设置</button></>}<div className="content-delivery-actions"><button aria-label="预览文稿" title="预览全部页面" disabled={busy||!pages.length} onClick={()=>run(previewDocument)}><Eye size={17} aria-hidden="true"/>预览</button><button className="primary" aria-label="导出 PPT" title="生成并下载多页 PowerPoint (.pptx)" disabled={busy||!pages.length} onClick={()=>run(exportDocument)}><FileDown size={17} aria-hidden="true"/>{exporting?'生成并下载中…':'导出 PPTX'}</button></div></header>
 {editable&&settings&&<Modal title="导航与交付设置" onClose={()=>Settings(false)}><div className="content-options"><div className="row">{(['cover','agenda','sectionDividers'] as const).map((key,i)=><label key={key}><input type="checkbox" disabled={busy} checked={content.spec.structurePolicy[key]} onChange={e=>draftSpec(s=>{s.structurePolicy[key]=e.target.checked;})}/>{['封面','导航页','章节页'][i]}</label>)}<label>交付方式<select value={mode} onChange={e=>{M(e.target.value);P(undefined);}}><option value="final">正式版本（需复核）</option><option value="draft">草稿</option></select></label><label>页码<select value={content.spec.numbering.mode} onChange={e=>draftSpec(s=>{s.numbering.mode=e.target.value;})}><option value="contentOnly">正文页码</option><option value="physical">物理页码</option></select></label><button disabled={busy} onClick={()=>run(()=>changeSpec(s=>{s.sections.push({id:crypto.randomUUID(),title:`章节 ${s.sections.length+1}`,order:s.sections.length});}))}>添加章节</button></div>{content.spec.sections.map((section:any)=><label className="content-section-name" key={section.id}>章节<input aria-label={`章节 ${section.order+1} 标题`} value={section.title} onChange={e=>draftSpec(s=>{s.sections.find((x:any)=>x.id===section.id).title=e.target.value;})}/></label>)}{pages.map((p:any,index:number)=><label className="content-section-name" key={p.instanceId}>第 {index+1} 页章节<select aria-label={`第 ${index+1} 页章节`} value={p.sectionId} onChange={e=>draftSpec(s=>{s.instances.find((x:any)=>x.instanceId===p.instanceId).sectionId=e.target.value;})}>{content.spec.sections.map((x:any)=><option key={x.id} value={x.id}>{x.title}</option>)}</select></label>)}</div></Modal>}
 <div className="content-layout"><aside className="content-pages" aria-label="文稿页面">{pages.map((p:any,index:number)=><article className={p.instanceId===active?'selected':''} key={p.instanceId} draggable={editable&&!busy} onDragStart={e=>e.dataTransfer.setData('application/x-slidebi-page',String(index))} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();const raw=e.dataTransfer.getData('application/x-slidebi-page');const from=Number(raw);if(editable&&raw!==''&&Number.isInteger(from))run(()=>reorder(from,index));}}><button className="content-page-select" disabled={busy} aria-label={`${editable?'编辑':'预览'}第 ${index+1} 页 ${p.title}`} title={editable?'拖动排列页面；Alt + 上下方向键调整顺序':p.title} onKeyDown={e=>{if(editable&&e.altKey&&['ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();run(()=>reorder(index,index+(e.key==='ArrowUp'?-1:1)));}}} onClick={()=>run(()=>select(p.slideId))}><PageThumbnail slideId={p.slideId} revision={p.revision}/><span>{index+1}. {p.title}</span></button>{editable&&<div className="content-page-actions"><button disabled={busy} title="复制页面" aria-label={`复制第 ${index+1} 页`} onClick={()=>run(()=>mutate('/import-pages',{sourceContentId:content.id,instanceIds:[p.instanceId]}))}><Copy size={14}/></button><button disabled={busy} title="删除页面" aria-label={`移除第 ${index+1} 页`} onClick={()=>{if(window.confirm(`确定删除第 ${index+1} 页「${p.title}」？`))run(()=>mutate(`/pages/${p.instanceId}/remove`));}}><Trash2 size={14}/></button></div>}</article>)}</aside><div className="content-editor" inert={busy||!!preview}>{!editable?(slide?<PageThumbnail slideId={slide.id} revision={slide.revision}/>:<p>文稿暂无页面</p>):slide?<Editor key={`${slide.id}:${editorEpoch}`} initial={slide} templates={templates} embedded frozen={busy||!!preview} registerFlush={registerFlush} onChanged={()=>P(undefined)} onSaved={saved=>{const update=(d:any)=>({...d,pages:d.pages.map((p:any)=>p.slideId===saved.id?{...p,title:saved.title,revision:saved.revision}:p)});contentRef.current=update(contentRef.current);C(update);P(undefined);}} onClose={()=>{}} onOpen={copy=>run(async()=>{await flushSpec();const current=contentRef.current;const d=await post(`/contents/${current.id}/pages`,{revision:current.revision,slideId:copy.id});C(d);await load(d.id,d.pages.find((p:any)=>p.slideId===copy.id)?.instanceId||d.pages.at(-1)?.instanceId);})} onExports={onExports}/>:<div className="empty"><button onClick={()=>W(true)}><Plus size={18}/>新增页面</button></div>}</div></div>
 </>}{busy&&<p role="status">正在保存和读取文稿…</p>}
 {wizard&&<AddPageDialog templates={templates} onImport={()=>{W(false);run(async()=>{await list();I(true);Source(undefined);Selected([]);});}} onClose={()=>W(false)} onCreated={s=>{W(false);run(async()=>{const d=await post(`/contents/${content.id}/pages`,{revision:content.revision,slideId:s.id});C(d);await load(d.id,d.pages.find((p:any)=>p.slideId===s.id)?.instanceId||d.pages.at(-1)?.instanceId);});}}/>}
 {importing&&<Modal title="从其他文稿导入页面" wide onClose={()=>I(false)}><label>来源文稿<select value={source?.id||''} onChange={e=>run(async()=>{Source(e.target.value?await api(`/contents/${e.target.value}`):undefined);Selected([]);})}><option value="">选择文稿</option>{items.filter(x=>x.id!==content.id).map(x=><option key={x.id} value={x.id}>{x.title||x.spec?.title}</option>)}</select></label><p>导入页面创建独立副本；数据源继续共享，页面修改互不影响。</p><div className="content-import-grid">{source?.pages.map((p:any)=><label key={p.instanceId}><input type="checkbox" checked={selected.includes(p.instanceId)} onChange={e=>Selected(e.target.checked?[...selected,p.instanceId]:selected.filter(id=>id!==p.instanceId))}/>{p.title}<PageThumbnail slideId={p.slideId} revision={p.revision}/></label>)}</div><button className="primary" disabled={busy||!selected.length} onClick={()=>run(async()=>{await mutate('/import-pages',{sourceContentId:source.id,instanceIds:selected});I(false);})}>导入所选 {selected.length} 页</button></Modal>}
 {preview&&<Modal title={`文稿预览 · ${preview.svgs?.length||0} 页`} wide onClose={()=>{PreviewFullscreen(false);P(undefined)}}><div className="content-preview-toolbar"><div className="row">{preview.svgs?.map((_:any,i:number)=><button key={i} onClick={()=>PP(i)}>第 {i+1} 页</button>)}</div><button type="button" aria-label="全屏预览当前页" title="全屏预览当前页" onClick={()=>PreviewFullscreen(true)}><Maximize2 size={17}/></button></div><div className="actual-preview" dangerouslySetInnerHTML={{__html:preview.svgs?.[previewPage]||''}}/>{previewFullscreen&&<div className="content-preview-fullscreen" role="region" aria-label={`全屏预览第 ${previewPage+1} 页`}><button type="button" aria-label="退出全屏预览" title="退出全屏预览" onClick={()=>PreviewFullscreen(false)}><Minimize2 size={19}/></button><div className="actual-preview" dangerouslySetInnerHTML={{__html:preview.svgs?.[previewPage]||''}}/></div>}{preview.diagnostics?.map((d:any,i:number)=><p key={i}>{d.message||d.code}</p>)}<footer>{editable&&mode==='final'&&<button className="primary" disabled={busy} onClick={()=>run(async()=>{const latest=await api(`/contents/${content.id}`);for(const p of latest.pages)await post(`/slides/${p.slideId}/review`,{revision:p.revision});await load(content.id,active);})}>确认文稿内容</button>}</footer></Modal>}
 </section>;
}
function PageThumbnail({slideId,revision}:{slideId:string;revision:number}){const[svg,S]=useState('');useEffect(()=>{let current=true;api(`/slides/${slideId}`).then(async s=>{const data=await api(`/data-snapshots/${s.snapshotRef}`);const compiled=compileSlide(s,data,'draft');compiled.assets=await Promise.all([...new Set(s.elements.filter((e:any)=>e.type==='image').map((e:any)=>e.assetId))].map(async id=>{const r=await fetch(`/api/assets/${id}/file`);if(!r.ok)throw new Error('资源加载失败');const blob=await r.blob();const dataUri=await new Promise<string>((resolve,reject)=>{const f=new FileReader();f.onload=()=>resolve(String(f.result));f.onerror=reject;f.readAsDataURL(blob);});return{id:String(id),dataUri};}));if(current)S(renderSlideSvg(compiled));}).catch(()=>{if(current)S('<span>预览暂不可用</span>');});return()=>{current=false;};},[slideId,revision]);return <div className="content-page-thumbnail" aria-hidden="true" dangerouslySetInnerHTML={{__html:svg||'<span>正在加载预览</span>'}}/>;}
