import React, {useEffect,useState} from 'react';
import {api,post} from './api';
import './deck.css';
type Section={id:string;title:string;order:number};
type Instance={instanceId:string;slideRef:{id:string;revision:number};sectionId:string;order:number;included:boolean};
type Spec={title:string;sections:Section[];instances:Instance[];structurePolicy:{cover:boolean;agenda:boolean;sectionDividers:boolean;agendaPageCapacity:number};numbering:{mode:'contentOnly'|'physical';showTotal:boolean}};
const ordered=<T extends {order:number}>(items:T[])=>[...items].sort((a,b)=>a.order-b.order);
export function DeckManagement({slides,onExports,onDirtyChange}:{slides:any[];onExports:()=>void;onDirtyChange?:(dirty:boolean)=>void}) {
 const [items,setItems]=useState<any[]>([]),[deck,setDeck]=useState<any>(),[spec,setSpec]=useState<Spec>(),[dirty,setDirty]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[preview,setPreview]=useState<any>(),[selectedPage,setSelectedPage]=useState(0),[creating,setCreating]=useState(false),[title,setTitle]=useState('经营汇报'),[selected,setSelected]=useState<string[]>([]),[appendId,setAppendId]=useState(''),[policy,setPolicy]=useState('latestRequired'),[mode,setMode]=useState('final');
 useEffect(()=>{onDirtyChange?.(dirty);const protect=(event:BeforeUnloadEvent)=>{if(dirty){event.preventDefault();event.returnValue='';}};window.addEventListener('beforeunload',protect);return()=>{window.removeEventListener('beforeunload',protect);onDirtyChange?.(false);};},[dirty,onDirtyChange]);
 const name=(id:string)=>slides.find(s=>s.id===id)?.title||id;
 async function reload(){setItems((await api('/decks')).items);}
 async function open(id:string){setBusy(true);setError('');try{const d=await api(`/decks/${id}`);setDeck(d);setSpec(d.spec);setDirty(false);setPreview(undefined);history.pushState({},'',`/decks/${id}`);}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 useEffect(()=>{reload().catch(e=>setError(e.message));const id=location.pathname.match(/^\/decks\/([^/]+)$/)?.[1];if(id)open(id);},[]);
 function change(fn:(s:Spec)=>void){if(!spec)return;const next=structuredClone(spec);fn(next);setSpec(next);setDirty(true);setPreview(undefined);}
 async function run(fn:()=>Promise<void>){setBusy(true);setError('');try{await fn();}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 async function save(){if(!dirty)return deck;const saved=await api(`/decks/${deck.id}`,{method:'PUT',body:JSON.stringify({revision:deck.revision,spec})});setDeck(saved);setSpec(saved.spec);setDirty(false);return saved;}
 function moveSection(id:string,delta:number){change(s=>{const list=ordered(s.sections),index=list.findIndex(x=>x.id===id),other=index+delta;if(other<0||other>=list.length)return;[list[index],list[other]]=[list[other],list[index]];list.forEach((x,i)=>x.order=i);});}
 function movePage(id:string,delta:number){change(s=>{const current=s.instances.find(x=>x.instanceId===id)!;const list=ordered(s.instances.filter(x=>x.sectionId===current.sectionId)),index=list.indexOf(current),other=index+delta;if(other<0||other>=list.length)return;[list[index],list[other]]=[list[other],list[index]];list.forEach((x,i)=>x.order=i);});}
 return <section className="deck-manager" aria-label="我的汇报">{error&&<div role="alert" className="error">{error}<p>若提示数据或结论待复核，请先在“我的页面”检查并确认；也可选择草稿预览。</p></div>}
 {!deck?<><div className="section-heading"><h2>我的汇报 <span>{items.length}</span></h2><button className="primary" disabled={busy} onClick={()=>setCreating(true)}>新建汇报</button></div>{creating&&<form className="deck-panel" onSubmit={e=>{e.preventDefault();run(async()=>{const d=await post('/decks',{title,slideIds:selected});setCreating(false);await open(d.id);});}}><h3>选择已有页面组成汇报</h3><label>新汇报标题<input required value={title} maxLength={80} onChange={e=>setTitle(e.target.value)}/></label><div className="deck-picker">{slides.map(s=><label key={s.id}><input type="checkbox" checked={selected.includes(s.id)} onChange={e=>setSelected(e.target.checked?[...selected,s.id]:selected.filter(id=>id!==s.id))}/>{s.title} · r{s.revision}</label>)}</div>{!slides.length&&<p>请先在“我的页面”创建并保存页面。</p>}<div className="row"><button className="primary" disabled={busy||!selected.length||!title.trim()}>创建汇报</button><button type="button" onClick={()=>setCreating(false)}>取消</button></div></form>}<div className="list">{items.map(d=><article key={d.id}><div><h3><button disabled={busy} onClick={()=>open(d.id)}>{d.title||d.spec?.title}</button></h3><p>r{d.revision} · {d.updatedAt?new Date(d.updatedAt).toLocaleString('zh-CN'):'已保存'}</p></div><button disabled={busy} aria-label={`归档 ${d.title||d.spec?.title}`} onClick={()=>run(async()=>{await post(`/decks/${d.id}/archive`);await reload();})}>归档</button></article>)}</div>{!items.length&&!creating&&<div className="empty"><h3>将页面整理成一份完整汇报</h3><p>自动生成封面、目录与章节页，统一页码并导出多页 PPTX。</p></div>}</>:spec&&<>
 <div className="section-heading"><button disabled={busy} onClick={()=>{if(dirty&&!window.confirm('有未保存的修改，确定返回吗？'))return;setDeck(undefined);setSpec(undefined);setPreview(undefined);history.pushState({},'','/decks');reload().catch(e=>setError(e.message));}}>← 汇报列表</button><span>r{deck.revision} · {dirty?'未保存':'已保存'}</span></div>
 <fieldset disabled={busy} className="deck-fieldset"><div className="deck-panel"><label>汇报标题<input value={spec.title} maxLength={80} onChange={e=>change(s=>{s.title=e.target.value;})}/></label><div className="deck-options">{(['cover','agenda','sectionDividers'] as const).map((key,i)=><label key={key}><input type="checkbox" checked={spec.structurePolicy[key]} onChange={e=>change(s=>{s.structurePolicy[key]=e.target.checked;})}/>{['封面','目录','章节页'][i]}</label>)}<label>每页目录章节数<select value={spec.structurePolicy.agendaPageCapacity} onChange={e=>change(s=>{s.structurePolicy.agendaPageCapacity=Number(e.target.value);})}>{[1,2,3,4,5,6,7,8].map(n=><option key={n} value={n}>{n}</option>)}</select></label><label>页码模式<select value={spec.numbering.mode} onChange={e=>change(s=>{s.numbering.mode=e.target.value as any;})}><option value="contentOnly">仅正文计数</option><option value="physical">所有页面计数</option></select></label><label><input type="checkbox" checked={spec.numbering.showTotal} onChange={e=>change(s=>{s.numbering.showTotal=e.target.checked;})}/>显示总页数</label></div></div>
 <div className="deck-layout"><div><div className="section-heading"><h3>章节与页面</h3><button onClick={()=>change(s=>{s.sections.push({id:crypto.randomUUID(),title:'新章节',order:s.sections.length});})}>添加章节</button></div>
 {ordered(spec.sections).map((section,si)=><section className="deck-panel" key={section.id}><div className="deck-section-heading"><label>章节 {si+1}<input aria-label={`章节 ${si+1} 标题`} maxLength={48} value={section.title} onChange={e=>change(s=>{s.sections.find(x=>x.id===section.id)!.title=e.target.value;})}/></label><button aria-label={`上移章节 ${section.title}`} disabled={si===0} onClick={()=>moveSection(section.id,-1)}>↑</button><button aria-label={`下移章节 ${section.title}`} disabled={si===spec.sections.length-1} onClick={()=>moveSection(section.id,1)}>↓</button><button disabled={spec.instances.some(i=>i.sectionId===section.id)} title="请先移走或移除章节内页面" onClick={()=>change(s=>{s.sections=s.sections.filter(x=>x.id!==section.id);s.sections=ordered(s.sections).map((x,i)=>({...x,order:i}));})}>删除章节</button></div>
 {ordered(spec.instances.filter(i=>i.sectionId===section.id)).map((instance,pi,array)=><div className="deck-instance" key={instance.instanceId}><label><input type="checkbox" aria-label={`纳入 ${name(instance.slideRef.id)}`} checked={instance.included} onChange={e=>change(s=>{s.instances.find(i=>i.instanceId===instance.instanceId)!.included=e.target.checked;})}/><span>{name(instance.slideRef.id)}<small>引用版本 r{instance.slideRef.revision}{policy==='latestRequired'?' · 预览时使用当前页面':''}</small></span></label><div className="row"><select aria-label={`移动 ${name(instance.slideRef.id)} 至章节`} value={instance.sectionId} onChange={e=>change(s=>{const i=s.instances.find(x=>x.instanceId===instance.instanceId)!;i.sectionId=e.target.value;i.order=Math.max(-1,...s.instances.filter(x=>x.sectionId===i.sectionId).map(x=>x.order))+1;})}>{ordered(spec.sections).map(x=><option key={x.id} value={x.id}>{x.title}</option>)}</select><button disabled={pi===0} aria-label={`上移 ${name(instance.slideRef.id)}`} onClick={()=>movePage(instance.instanceId,-1)}>↑</button><button disabled={pi===array.length-1} aria-label={`下移 ${name(instance.slideRef.id)}`} onClick={()=>movePage(instance.instanceId,1)}>↓</button><button aria-label={`移除 ${name(instance.slideRef.id)}`} onClick={()=>change(s=>{s.instances=s.instances.filter(x=>x.instanceId!==instance.instanceId);})}>移除</button></div></div>)}
 {!spec.instances.some(i=>i.sectionId===section.id)&&<p className="muted">空章节不生成章节页。</p>}</section>)}
 <div className="deck-panel"><label>追加已有页面<select value={appendId} onChange={e=>setAppendId(e.target.value)}><option value="">选择页面，可重复使用</option>{slides.map(s=><option key={s.id} value={s.id}>{s.title} · r{s.revision}</option>)}</select></label><button disabled={!appendId||!spec.sections.length} onClick={()=>change(s=>{const slide=slides.find(x=>x.id===appendId);const sectionId=ordered(s.sections)[s.sections.length-1].id;s.instances.push({instanceId:crypto.randomUUID(),slideRef:{id:slide.id,revision:slide.revision},sectionId,order:Math.max(-1,...s.instances.filter(x=>x.sectionId===sectionId).map(x=>x.order))+1,included:true});})}>追加到最后章节</button></div></div>
 <div><div className="deck-panel"><h3>数据与交付</h3><p className="muted">可使用当前页面与最新数据，或复用引用版本。BI 刷新当前使用 Mock。</p><label>数据策略<select value={policy} onChange={e=>{setPolicy(e.target.value);setPreview(undefined);}}><option value="latestRequired">使用当前页面与最新数据（检查 BI 更新）</option><option value="snapshot">使用引用页面版本中的数据</option></select></label><label>交付方式<select value={mode} onChange={e=>{setMode(e.target.value);setPreview(undefined);}}><option value="final">正式版本（需完成复核）</option><option value="draft">草稿（带水印）</option></select></label><p>预览后数据与页面将冻结。本次导出使用同一份预览；重新预览可获取新数据。</p><div className="row"><button disabled={!dirty||!spec.title.trim()} onClick={()=>run(async()=>{await save();})}>保存汇报</button><button className="primary" disabled={!spec.title.trim()||!spec.instances.some(i=>i.included)} onClick={()=>run(async()=>{setPreview(undefined);const saved=await save();const result=await post(`/decks/${deck.id}/preview`,{revision:saved.revision,dataPolicy:policy,deliveryMode:mode});setPreview(result);setSelectedPage(0);})}>保存并预览</button><button disabled={!preview||dirty||preview.diagnostics?.some((d:any)=>d.severity==='error')} onClick={()=>run(async()=>{await post(`/decks/${deck.id}/export`,{revision:deck.revision,previewId:preview.previewId,deliveryMode:mode});onExports();})}>导出 PPTX</button></div></div>
 {preview&&<div className="deck-panel"><h3>汇报预览 · {preview.svgs?.length||0} 页</h3>{preview.diagnostics?.map((d:any,i:number)=><p key={i} className={d.severity==='error'?'error':'muted'}>{d.message||d.code}</p>)}<div className="deck-pagination">{preview.svgs?.map((_:any,i:number)=><button className={i===selectedPage?'active':''} key={i} onClick={()=>setSelectedPage(i)}>第 {i+1} 页</button>)}</div><p>物理页码 {selectedPage+1} · 显示页码 {preview.slides?.[selectedPage]?.provenance?.displayNumber??preview.slides?.[selectedPage]?.displayPageNumber??preview.slides?.[selectedPage]?.displayNumber??'无'}</p><div className="deck-preview" dangerouslySetInnerHTML={{__html:preview.svgs?.[selectedPage]||''}}/><details><summary>查看页面与数据溯源</summary><pre>{JSON.stringify(preview.provenance,null,2)}</pre></details></div>}</div></div></fieldset>{busy&&<p role="status">正在处理汇报…</p>}</>}
 </section>;
}
