// @vitest-environment jsdom
import React from 'react';
import {render,screen,fireEvent,waitFor,cleanup} from '@testing-library/react';
import {it,expect,vi,afterEach} from 'vitest';
import {DeckManagement} from './DeckManagement';
import {api,post} from './api';
vi.mock('./api',()=>({api:vi.fn(),post:vi.fn()}));
afterEach(()=>{cleanup();vi.resetAllMocks();history.replaceState({},'', '/decks');});
const spec={title:'经营月报',sections:[{id:'section',title:'经营概览',order:0}],instances:[{instanceId:'i1',slideRef:{id:'s1',revision:1},sectionId:'section',order:0,included:true},{instanceId:'i2',slideRef:{id:'s2',revision:2},sectionId:'section',order:1,included:true}],structurePolicy:{cover:true,agenda:true,sectionDividers:true,agendaPageCapacity:8},numbering:{mode:'contentOnly',showTotal:true}};
const deck={id:'d1',revision:1,spec};
function setup(){vi.mocked(api).mockImplementation(async(path,init)=>path==='/decks'?{items:[{...deck,title:spec.title}]}:init?.method==='PUT'?{...deck,revision:2,spec:JSON.parse(String(init.body)).spec}:structuredClone(deck));vi.mocked(post).mockResolvedValue({previewId:'p1',svgs:['<svg xmlns="http://www.w3.org/2000/svg"><text>预览内容</text></svg>'],slides:[{kind:'content',physicalPage:1,displayPageNumber:1}],diagnostics:[],navigation:[]});render(<DeckManagement slides={[{id:'s1',title:'收入分析',revision:1},{id:'s2',title:'趋势分析',revision:2}]} onExports={vi.fn()}/>);}
it('invalidates frozen preview after edits',async()=>{setup();fireEvent.click(await screen.findByRole('button',{name:'经营月报'}));fireEvent.click(await screen.findByRole('button',{name:'保存并预览'}));await screen.findByText('预览内容');expect(post).toHaveBeenCalledWith('/decks/d1/preview',expect.objectContaining({dataPolicy:'latestRequired',revision:1}));fireEvent.change(screen.getByLabelText('汇报标题'),{target:{value:'新标题'}});expect(screen.queryByText('预览内容')).toBeNull();expect((screen.getByRole('button',{name:'导出 PPTX'}) as HTMLButtonElement).disabled).toBe(true);});
it('persists reordered instances before preview and exports frozen preview',async()=>{setup();fireEvent.click(await screen.findByRole('button',{name:'经营月报'}));fireEvent.click(await screen.findByRole('button',{name:'下移 收入分析'}));fireEvent.click(screen.getByRole('button',{name:'保存并预览'}));await screen.findByText('预览内容');const call=vi.mocked(api).mock.calls.find(c=>c[1]?.method==='PUT');expect(call).toBeTruthy();const body=JSON.parse(String(call![1]!.body));expect(body.spec.instances.find((i:any)=>i.instanceId==='i1').order).toBe(1);expect(body.spec.instances.find((i:any)=>i.instanceId==='i2').order).toBe(0);fireEvent.click(screen.getByRole('button',{name:'导出 PPTX'}));await waitFor(()=>expect(post).toHaveBeenCalledWith('/decks/d1/export',{revision:2,previewId:'p1',deliveryMode:'final'}));});
it('keeps section order stable at boundaries and persists agenda capacity',async()=>{setup();fireEvent.click(await screen.findByRole('button',{name:'经营月报'}));expect((await screen.findByRole('button',{name:'上移章节 经营概览'}) as HTMLButtonElement).disabled).toBe(true);fireEvent.click(screen.getByRole('button',{name:'添加章节'}));fireEvent.change(screen.getByLabelText('章节 2 标题'),{target:{value:'趋势'}});fireEvent.click(screen.getByRole('button',{name:'上移章节 趋势'}));expect((screen.getByLabelText('章节 1 标题') as HTMLInputElement).value).toBe('趋势');fireEvent.change(screen.getByLabelText('每页目录章节数'),{target:{value:'3'}});fireEvent.click(screen.getByRole('button',{name:'保存汇报'}));await waitFor(()=>expect(api).toHaveBeenCalledWith('/decks/d1',expect.objectContaining({method:'PUT'})));const body=JSON.parse(String(vi.mocked(api).mock.calls.find(c=>c[1]?.method==='PUT')![1]!.body));expect(body.spec.sections.find((s:any)=>s.title==='趋势').order).toBe(0);expect(body.spec.structurePolicy.agendaPageCapacity).toBe(3);});
it('clears a frozen preview on policy changes and reports unsaved changes',async()=>{const dirty=vi.fn();vi.mocked(api).mockResolvedValue(deck);history.replaceState({},'','/decks/d1');vi.mocked(api).mockImplementation(async path=>path==='/decks'?{items:[]}:structuredClone(deck));vi.mocked(post).mockResolvedValue({previewId:'p1',svgs:['<svg><text>预览内容</text></svg>'],slides:[{provenance:{displayNumber:3}}],diagnostics:[]});render(<DeckManagement slides={[]} onExports={vi.fn()} onDirtyChange={dirty}/>);fireEvent.click(await screen.findByRole('button',{name:'保存并预览'}));await screen.findByText('预览内容');expect(screen.getByText(/显示页码 3/)).toBeTruthy();fireEvent.change(screen.getByLabelText('数据策略'),{target:{value:'snapshot'}});expect(screen.queryByText('预览内容')).toBeNull();fireEvent.change(screen.getByLabelText('汇报标题'),{target:{value:'编辑中'}});await waitFor(()=>expect(dirty).toHaveBeenLastCalledWith(true));});
