import {validateDataSpec} from '@slidebi/presentation';
export const tableSample={schema:[{name:'月份',type:'string'},{name:'实际收入',type:'number',unit:'万元'},{name:'预算收入',type:'number',unit:'万元'}],rows:[['1月',120,130],['2月',145,140],['3月',158,150]]};
export function toDataSpec(input:any):any{
 if(input?.resultSets)return input;
 if(!Array.isArray(input?.schema)||!input.schema.length||!Array.isArray(input.rows))throw new Error('请提供 schema 字段列表和 rows 数据行，或完整 DataSpec。');
 const names=new Set<string>();const fields=input.schema.map((f:any,i:number)=>{if(typeof f?.name!=='string'||!f.name.trim())throw new Error('每列必须提供 name。');if(names.has(f.name))throw new Error('字段名称不能重复。');names.add(f.name);const type=f.type==='number'?'decimal':f.type;if(!['string','integer','decimal','date','datetime','boolean'].includes(type))throw new Error(`字段 ${f.name} 类型不支持。`);return{id:`f${i+1}`,name:f.name,type,nullable:true,semanticRef:`${['decimal','integer'].includes(type)?'measure':'column'}-${i+1}`}});
 const rows=input.rows.map((row:any,index:number)=>{if(Array.isArray(row)?row.length!==fields.length:!row||typeof row!=='object'||Object.keys(row).length!==fields.length||fields.some((f:any)=>!Object.hasOwn(row,f.name)))throw new Error(`第 ${index+1} 行列数或字段与 schema 不一致。`);return Object.fromEntries(fields.map((f:any,i:number)=>{const value=Array.isArray(row)?row[i]:row[f.name];return[f.id,f.type==='decimal'&&typeof value==='number'&&Number.isFinite(value)?String(value):value]}))});
 const numeric=(f:any)=>['decimal','integer'].includes(f.type);const keys=fields.filter((f:any)=>!numeric(f)).map((f:any)=>f.id);if(!keys.length)keys.push(fields[0].id);
 const now=new Date().toISOString();const data={specVersion:'1.0',id:'manual-table',mode:'snapshot',source:{system:'manual',modelId:'manual-table',modelRevision:'1'},snapshot:{id:'manual-import',capturedAt:now,dataAsOf:null,consistency:'importedSnapshot'},context:{locale:'zh-CN',timezone:'Asia/Shanghai',parameters:{},filters:[],effectiveFilters:[]},semanticSchema:{coverage:'referencedSubset',tables:[{id:'manual',name:'人工导入表格',columns:fields.filter((f:any)=>!numeric(f)).map((f:any)=>({id:f.semanticRef,name:f.name,type:f.type}))}],relationships:[]},measures:fields.filter(numeric).map((f:any)=>({id:f.semanticRef,name:f.name,dax:'BLANK()',description:'人工输入值；不执行 DAX 计算。',unit:{baseUnit:input.schema[fields.indexOf(f)].unit||'数值'},format:{displayDivisor:'1',decimals:f.type==='integer'?0:2,suffix:'',percent:false},aggregationBehavior:'nonAdditive',favorableDirection:'neutral',dependencies:[]})),queries:[{id:'manual-input',provider:'manual',definition:{kind:'importedTable'},effectiveFilters:[]}],resultSets:[{id:'table',queryId:'manual-input',name:input.name||'人工导入表格',fields,rows,grain:keys,primaryKey:keys,truncated:false}]};
 const result=validateDataSpec(data);if(!result.valid)throw new Error(`表格校验失败：${result.errors.map(e=>`${e.path||''} ${e.message}`).join('；')}。分类字段组合应唯一，类型与数据需一致。`);return data;
}
