import React,{useRef,useState} from 'react';
import {Trash2,Star,Upload,Search} from 'lucide-react';
import {api} from './api';
import {TemplateThumbnail} from './TemplateThumbnail';
import {TemplateEditor} from './TemplateEditor';
import {Modal} from './ui';
import {LibraryToolbar,useLibraryNavigation} from './LibraryNavigation';
export function TemplateLibrary({templates,onRefresh,onError}:{templates:any[];onRefresh:()=>void;onError?:(message:string)=>void}){
 const nav=useLibraryNavigation(),upload=useRef<HTMLInputElement>(null);
 const [importing,I]=useState(false),[search,Q]=useState(''),[edit,E]=useState<string>(),[error,X]=useState(''),[renaming,N]=useState<string>(),[name,S]=useState('');
 const run=async(fn:()=>Promise<any>)=>{X('');try{await fn();onRefresh()}catch(e:any){X(e.message);onError?.(e.message)}};
 const rename=(t:any)=>run(async()=>{if(name.trim()&&name.trim()!==t.name)await api(`/templates/${t.id}/metadata`,{method:'PATCH',body:JSON.stringify({expectedVersion:t.version,name})});N(undefined)});
 const example=()=>run(async()=>{if(!templates[0])throw new Error('暂无可用模板示例');const payload=await api(`/templates/${templates[0].id}`);const url=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}));const link=document.createElement('a');link.href=url;link.download='模板导入示例.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)});
 return <><LibraryToolbar actions={<button title="导入模板 JSON" aria-label="导入模板" onClick={()=>I(true)}><Upload size={18}/></button>}><label className="search"><Search size={16}/><input aria-label="搜索模板" value={search} onChange={e=>Q(e.target.value)} placeholder="搜索模板名称"/></label></LibraryToolbar><input ref={upload} type="file" accept=".json,application/json" hidden onChange={e=>{const file=e.target.files?.[0];if(file)run(async()=>{const payload=JSON.parse(await file.text());await api('/templates/import',{method:'POST',body:JSON.stringify({...payload,folderId:nav.folderId||null})});I(false)});e.target.value=''}}/>{error&&<p role="alert" className="error">{error}</p>}<div className="slide-grid">{templates.filter(t=>(!nav.managed||(t.folderId??null)===nav.folderId)&&t.name.toLowerCase().includes(search.trim().toLowerCase())).map(t=><article className="slide-card" key={`${t.id}-${t.version}`}><button className="thumbnail" title={t.canEdit?'预览与编辑':'预览'} aria-label={`预览 ${t.name}`} onClick={()=>E(t.id)}><TemplateThumbnail templateId={t.id} name={t.name}/></button><div className="card-info"><div className="template-card-name">{renaming===t.id?<input autoFocus aria-label="模板名称" value={name} onChange={e=>S(e.target.value)} onBlur={()=>rename(t)} onKeyDown={e=>{if(e.key==='Enter')e.currentTarget.blur();if(e.key==='Escape')N(undefined)}}/>:<h3 onDoubleClick={()=>{if(t.canEdit){N(t.id);S(t.name)}}} title={t.canEdit?'双击修改名称':t.name}>{t.name}</h3>}<button title={t.favorite?'取消收藏':'收藏'} aria-label={`收藏 ${t.name}`} onClick={()=>run(()=>api(`/templates/${t.id}/favorite`,{method:t.favorite?'DELETE':'PUT'}))}><Star size={17} fill={t.favorite?'currentColor':'none'}/></button>{t.canDelete&&<button title="删除" aria-label={`删除 ${t.name}`} onClick={()=>{if(window.confirm(`确定删除模板「${t.name}」？已有文稿仍保留原页面。`))run(()=>api(`/templates/${t.id}`,{method:'DELETE',body:JSON.stringify({expectedVersion:t.version})}))}}><Trash2 size={17}/></button>}</div></div></article>)}</div>{importing&&<Modal title="导入模板" onClose={()=>I(false)}><p>上传自包含模板 JSON，包含业务背景、页面布局和配套样例数据。可下载现有模板作为格式示例。</p><p className="muted">当前支持 JSON 模板，不支持直接导入 PPTX。</p><div className="row"><button disabled={!templates.length} onClick={example}>下载格式示例</button><button className="primary" onClick={()=>upload.current?.click()}>选择 JSON 文件</button></div>{error&&<p role="alert" className="error">{error}</p>}</Modal>}{edit&&<TemplateEditor templateId={edit} onClose={()=>{E(undefined);onRefresh()}} onSaved={()=>{onRefresh()}}/>}</>
}
