import React,{useEffect,useState} from 'react';
import {compileSlide,renderSlideSvg} from '@slidebi/presentation';
import {api} from './api';
import {Modal} from './ui';
import {Star,Trash2,Pencil,Eye,Maximize2,Globe,LockKeyhole,Save,Folder} from 'lucide-react';
import {TemplateDataTable} from './TemplateDataTable';
import {TemplateCanvasEditor} from './TemplateCanvasEditor';
import './template-editor.css';
import {FolderPicker,useLibraryNavigation} from './LibraryNavigation';
export function TemplateEditor({templateId,onClose,onSaved}:{templateId:string;onClose:()=>void;onSaved:()=>void}){
 const nav=useLibraryNavigation();
 const [draft,D]=useState<any>(),[zoom,Z]=useState(false),[editing,C]=useState(false),[folder,F]=useState(false),[confirm,Q]=useState(false),[error,E]=useState(''),[busy,B]=useState(false),[dirty,S]=useState(false),[assets,A]=useState<any[]>([]);
 useEffect(()=>{let active=true;api(`/templates/${templateId}`).then(t=>{if(active)D(t)}).catch(e=>E(e.message));return()=>{active=false}},[templateId]);
 useEffect(()=>{let active=true;if(!draft)return;const ids=[...new Set(draft.example.slide.elements.filter((e:any)=>e.type==='image').map((e:any)=>e.assetId))];Promise.all(ids.map(async id=>{const response=await fetch(`/api/assets/${id}/file`);if(!response.ok)throw new Error('图片资源加载失败');const blob=await response.blob();const dataUri=await new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result));r.onerror=reject;r.readAsDataURL(blob)});return {id,dataUri}})).then(a=>{if(active)A(a)}).catch(e=>{if(active)E(e.message)});return()=>{active=false}},[draft?.id]);
 const change=(fn:(next:any)=>void)=>{D((old:any)=>{const next=structuredClone(old);fn(next);return next});S(true)};
 let svg='',previewError='';try{if(draft?.example){const compiled=compileSlide(draft.example.slide,draft.example.dataSpec,'draft');const issues=compiled.diagnostics?.filter(d=>d.severity==='error')||[];if(issues.length)throw new Error(issues.map(d=>d.message).join('；'));compiled.assets=assets;const footers=new Set(draft.example.slide.elements.filter((e:any)=>e.type==='sourceFooter').map((e:any)=>e.id));compiled.elements=compiled.elements.filter((e:any)=>e.id!=='draft-watermark'&&!footers.has(e.id));svg=renderSlideSvg(compiled)}}catch(e:any){previewError=`页面预览暂不可用，请检查字段类型、数据及页面设置：${e.message||'数据格式不匹配'}`}
 const close=()=>{if(busy)return;if(dirty)Q(true);else onClose()};
 const save=async(closeAfter=false)=>{if(busy||!draft?.canEdit)return;B(true);E('');try{const updated=await api(`/templates/${templateId}`,{method:'PUT',body:JSON.stringify({expectedVersion:draft.version,name:draft.name,visibility:draft.visibility,folderId:draft.folderId||null,example:draft.example})});D({...updated,favorite:draft.favorite});S(false);Q(false);onSaved();if(closeAfter)onClose()}catch(e:any){E(e.message)}finally{B(false)}};
 useEffect(()=>{const listener=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='s'){e.preventDefault();if(draft?.canEdit&&dirty&&!busy)void save()}};window.addEventListener('keydown',listener);return()=>window.removeEventListener('keydown',listener)},[draft,dirty,busy]);
 useEffect(()=>{if(!dirty)return;const listener=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue=''};window.addEventListener('beforeunload',listener);return()=>window.removeEventListener('beforeunload',listener)},[dirty]);
 const favorite=async()=>{try{await api(`/templates/${templateId}/favorite`,{method:draft.favorite?'DELETE':'PUT'});D((old:any)=>({...old,favorite:!old.favorite}));onSaved()}catch(e:any){E(e.message)}};
 const remove=async()=>{if(!window.confirm(`确定删除模板「${draft.name}」？已有文稿仍保留原页面。`))return;try{await api(`/templates/${templateId}`,{method:'DELETE',body:JSON.stringify({expectedVersion:draft.version})});onSaved();onClose()}catch(e:any){E(e.message)}};
 return <><Modal title={draft?.name||'模板预览'} wide header={draft?<div className="template-detail-header"><div className="template-title-line">{draft.canEdit?<input className="template-title-input" disabled={busy} aria-label="模板名称" value={draft.name} onChange={e=>change(d=>d.name=e.target.value)}/>:<h2>{draft.name}</h2>}<button disabled={!draft.canEdit||busy} title="选择模板目录" aria-label="选择模板目录" onClick={()=>F(true)}><Folder size={16}/><span>{nav.folders.find(f=>f.id===draft.folderId)?.name||'根目录'}</span></button><button disabled={!draft.canEdit||busy} title={draft.visibility==='public'?'公开：点击设为私有':'私有：点击设为公开'} aria-label="切换模板可见性" onClick={()=>change(d=>d.visibility=d.visibility==='public'?'private':'public')}>{draft.visibility==='public'?<Globe size={18}/>:<LockKeyhole size={18}/>}</button></div><div className="template-detail-actions"><span title={draft.canEdit?'可编辑':'只读预览'} aria-label={draft.canEdit?'可编辑':'只读预览'}>{draft.canEdit?<Pencil size={17}/>:<Eye size={17}/>}</span><span className="muted">{dirty?'未保存':`v${draft.version}`}</span><button title={draft.favorite?'取消收藏':'收藏'} aria-label="收藏模板" disabled={busy} onClick={favorite}><Star size={17} fill={draft.favorite?'currentColor':'none'}/></button>{draft.canDelete&&<button title="删除模板" aria-label="删除模板" disabled={busy} onClick={remove}><Trash2 size={17}/></button>}{draft.canEdit&&<button className="primary" title="保存模板（Ctrl / ⌘ S）" aria-label="保存模板" disabled={busy||!dirty} onClick={()=>save()}><Save size={18}/></button>}</div></div>:undefined} onClose={close}>{error&&<p role="alert" className="error">{error}</p>}{draft&&<fieldset className="template-detail" disabled={busy}>
 <section className="template-preview-section"><div className="template-preview-actions"><button title="全屏预览" aria-label="全屏预览" disabled={!!previewError} onClick={()=>Z(true)}><Maximize2 size={18}/></button>{draft.canEdit&&<button title="编辑模板页面" aria-label="编辑模板页面" onClick={()=>C(true)}><Pencil size={18}/></button>}</div>{previewError?<p className="error" role="alert">{previewError}</p>:<div className="actual-preview" dangerouslySetInnerHTML={{__html:svg}}/>}</section>
 <section className="template-context-section"><h3>业务背景与适用场景</h3>{draft.canEdit?<><label className="field">业务背景<textarea value={draft.example.businessContext.background} onChange={e=>change(d=>d.example.businessContext.background=e.target.value)}/></label><label className="field">适用场景（每行一项）<textarea value={draft.example.businessContext.scenarios.join('\n')} onChange={e=>change(d=>d.example.businessContext.scenarios=e.target.value.split('\n'))}/></label></>:<><h4>业务背景</h4><p>{draft.example.businessContext.background}</p><h4>适用场景</h4><div className="scenario-chips">{draft.example.businessContext.scenarios.map((s:string)=><span key={s}>{s}</span>)}</div></>}</section>
 <section><h3>模板数据</h3><p className="muted">{draft.example.dataSpec.resultSets.length} 张数据表 · 共 {draft.example.dataSpec.resultSets.reduce((n:number,r:any)=>n+r.rows.length,0)} 行 · {draft.example.dataSpec.resultSets.reduce((n:number,r:any)=>n+r.fields.length,0)} 个字段</p>{draft.example.dataSpec.resultSets.map((r:any,i:number)=><TemplateDataTable key={r.id} result={r} dataSpec={draft.example.dataSpec} editable={draft.canEdit&&!busy} onChange={next=>change(d=>d.example.dataSpec.resultSets[i]=next)}/>)}</section>
 </fieldset>}</Modal>{folder&&draft&&<FolderPicker kind="templates" value={draft.folderId||null} onChange={id=>change(d=>d.folderId=id)} onClose={()=>F(false)}/>}{zoom&&<div className="template-fullscreen"><Modal title="模板全屏预览" wide onClose={()=>Z(false)}><div className="actual-preview" dangerouslySetInnerHTML={{__html:svg}}/></Modal></div>}{editing&&draft?.canEdit&&<TemplateCanvasEditor slide={draft.example.slide} svg={svg} onChange={slide=>change(d=>d.example.slide=slide)} onClose={()=>C(false)}/>}{confirm&&<Modal title="保存模板修改？" onClose={()=>Q(false)}><p>模板有尚未保存的修改。</p>{error&&<p role="alert" className="error">{error}</p>}<div className="row"><button disabled={busy} onClick={()=>Q(false)}>继续编辑</button><button disabled={busy} onClick={onClose}>放弃修改</button><button className="primary" disabled={busy} onClick={()=>save(true)}>保存并关闭</button></div></Modal>}</>
}
