// @vitest-environment jsdom
import React from 'react';
import {render,screen,fireEvent,cleanup} from '@testing-library/react';
import {test,expect,vi,afterEach} from 'vitest';
import {TemplateDataTable} from './TemplateDataTable';
afterEach(cleanup);
const data={id:'r',primaryKey:['category'],fields:[{id:'category',name:'分类',type:'string',nullable:false},{id:'value',name:'金额',type:'decimal',nullable:true,unit:'元',description:'营业收入'}],rows:[{category:'华东',value:12}]};
test('one table shows field metadata in headers and opens owner schema editor',()=>{const change=vi.fn();render(<TemplateDataTable result={data} editable onChange={change}/>);expect(screen.getAllByRole('table')).toHaveLength(1);fireEvent.click(screen.getByRole('button',{name:'编辑字段 金额'}));fireEvent.change(screen.getByLabelText('字段说明'),{target:{value:'含税收入'}});fireEvent.click(screen.getByRole('button',{name:'应用字段设置'}));expect(change.mock.calls[0][0].fields[1].description).toBe('含税收入');});
test('uses a calculator metaphor for numeric fields instead of a hash mark',()=>{render(<TemplateDataTable result={data}/>);expect(document.querySelector('.lucide-calculator')).toBeTruthy();expect(document.querySelector('.lucide-hash')).toBeNull();expect(screen.getByLabelText('数值类型 decimal')).toBeTruthy()});
test('readonly template sample cannot edit schema or values',()=>{render(<TemplateDataTable result={data}/>);expect(screen.queryByRole('button',{name:/编辑字段/})).toBeNull();expect(screen.queryByRole('textbox')).toBeNull();expect(screen.getByText('华东')).toBeTruthy()});
test('uses the same semantic field name as chart binding controls',()=>{const result={id:'budget',primaryKey:['regionId'],fields:[{id:'regionId',type:'string',semanticRef:'region-id'},{id:'actual',type:'decimal',semanticRef:'revenue-actual'}],rows:[{regionId:'east',actual:'12'}]};const dataSpec={semanticSchema:{tables:[{columns:[{id:'region-id',name:'区域'}]}]},measures:[{id:'revenue-actual',name:'实际收入'}]};render(<TemplateDataTable result={result} dataSpec={dataSpec}/>);expect(screen.getByText('区域')).toBeTruthy();expect(screen.getByText('实际收入')).toBeTruthy();expect(screen.queryByText('regionId')).toBeNull();expect(screen.queryByText('actual')).toBeNull()});
test('renames a field display label while preserving its stable field id',()=>{const change=vi.fn();const result={id:'budget',primaryKey:['regionId'],fields:[{id:'regionId',type:'string',nullable:false,semanticRef:'region-id'},{id:'actual',type:'decimal',nullable:false,semanticRef:'revenue-actual'}],rows:[{regionId:'east',actual:'12'}]};const dataSpec={semanticSchema:{tables:[{columns:[{id:'region-id',name:'区域'}]}]},measures:[{id:'revenue-actual',name:'实际收入'}]};const {rerender}=render(<TemplateDataTable result={result} dataSpec={dataSpec} editable onChange={change}/>);fireEvent.click(screen.getByRole('button',{name:'编辑字段 实际收入'}));expect((screen.getByLabelText('字段名称') as HTMLInputElement).value).toBe('实际收入');fireEvent.change(screen.getByLabelText('字段名称'),{target:{value:'确认收入'}});fireEvent.click(screen.getByRole('button',{name:'应用字段设置'}));const changed=change.mock.calls[0][0];expect(changed.fields[1]).toMatchObject({id:'actual',semanticRef:'revenue-actual',name:'确认收入'});expect(changed.rows[0]).toEqual({regionId:'east',actual:'12'});rerender(<TemplateDataTable result={changed} dataSpec={dataSpec} editable onChange={change}/>);expect(screen.getByRole('button',{name:'编辑字段 确认收入'})).toBeTruthy();});
test('renames a data table while preserving its stable result-set id',()=>{const change=vi.fn();render(<TemplateDataTable result={data} editable onChange={change}/>);fireEvent.change(screen.getByRole('textbox',{name:'数据表名称'}),{target:{value:'月度收入明细'}});fireEvent.blur(screen.getByRole('textbox',{name:'数据表名称'}));expect(change).toHaveBeenCalledWith(expect.objectContaining({id:'r',name:'月度收入明细'}));expect(change.mock.calls[0][0].fields).toEqual(data.fields);expect(change.mock.calls[0][0].rows).toEqual(data.rows)});
test('field help appears on hover and schema opens a dismissible popover with numeric formatting choices',()=>{const change=vi.fn();render(<TemplateDataTable result={data} editable onChange={change}/>);const heading=screen.getByRole('button',{name:'编辑字段 金额'});fireEvent.mouseEnter(heading);expect(screen.getByRole('tooltip').textContent).toContain('营业收入');fireEvent.click(heading);expect(screen.getByRole('dialog',{name:'字段设置 金额'})).toBeTruthy();fireEvent.change(screen.getByLabelText('字段单位'),{target:{value:'CNY'}});fireEvent.click(screen.getByLabelText('千分位分隔'));fireEvent.change(screen.getByLabelText('小数位数'),{target:{value:'2'}});fireEvent.click(screen.getByRole('button',{name:'应用字段设置'}));const changed=change.mock.calls[0][0];expect(changed.fields[1]).toMatchObject({unit:'CNY',displayFormat:{useGrouping:true,decimalPlaces:2}});expect(changed.rows).toEqual(data.rows);fireEvent.click(heading);fireEvent.keyDown(screen.getByRole('dialog'),{key:'Escape'});expect(screen.queryByRole('dialog')).toBeNull()});
test('non numeric fields cannot choose units and formatting is applied only to display',()=>{const formatted=structuredClone(data) as any;formatted.fields[1].unit='USD';formatted.fields[1].displayFormat={useGrouping:true,decimalPlaces:2};formatted.rows[0].value='1234.5';const {rerender}=render(<TemplateDataTable result={formatted}/>);expect(screen.getByText('$1,234.50')).toBeTruthy();rerender(<TemplateDataTable result={formatted} editable/>);fireEvent.click(screen.getByRole('button',{name:'编辑字段 分类'}));expect((screen.getByLabelText('字段单位') as HTMLSelectElement).disabled).toBe(true);expect(screen.getByRole('textbox',{name:'字段名称'})).toBeTruthy();expect(screen.getByLabelText('允许空值')).toBeTruthy()});
test('incompatible type changes stay in the editor and explain the invalid row instead of corrupting values',()=>{const change=vi.fn();render(<TemplateDataTable result={data} editable onChange={change}/>);fireEvent.click(screen.getByRole('button',{name:'编辑字段 分类'}));fireEvent.change(screen.getByLabelText('字段类型'),{target:{value:'integer'}});fireEvent.click(screen.getByRole('button',{name:'应用字段设置'}));expect(change).not.toHaveBeenCalled();expect(screen.getByRole('alert').textContent).toContain('第 1 行');expect(screen.getByRole('dialog')).toBeTruthy()});
test('integer cell keeps a typing buffer and boolean uses explicit choices',()=>{const change=vi.fn();const result={id:'r',fields:[{id:'n',name:'数量',type:'integer',nullable:false},{id:'b',name:'生效',type:'boolean',nullable:true}],rows:[{n:1,b:false}]};render(<TemplateDataTable result={result} editable onChange={change}/>);const input=screen.getByLabelText('r 第1行 数量');fireEvent.focus(input);fireEvent.change(input,{target:{value:'-'}});expect((input as HTMLInputElement).value).toBe('-');expect(change).not.toHaveBeenCalled();fireEvent.change(input,{target:{value:'-12'}});fireEvent.blur(input);expect(change.mock.calls[0][0].rows[0].n).toBe(-12);fireEvent.change(screen.getByRole('combobox',{name:'r 第1行 生效'}),{target:{value:'true'}});expect(change.mock.calls[1][0].rows[0].b).toBe(true)});
test('schema popover traps Tab without bubbling into its parent modal',()=>{const parent=vi.fn();render(<div onKeyDown={parent}><TemplateDataTable result={data} editable/></div>);fireEvent.click(screen.getByRole('button',{name:'编辑字段 金额'}));const last=screen.getByRole('button',{name:'应用字段设置'});last.focus();fireEvent.keyDown(last,{key:'Tab'});expect(document.activeElement).toBe(screen.getByRole('button',{name:'关闭字段设置'}));expect(parent).not.toHaveBeenCalled()});
test('losing editability closes an open schema popover and discards its unsubmitted changes',()=>{const change=vi.fn();const {rerender}=render(<TemplateDataTable result={data} editable onChange={change}/>);fireEvent.click(screen.getByRole('button',{name:'编辑字段 金额'}));fireEvent.change(screen.getByLabelText('字段说明'),{target:{value:'保存中不应写入'}});rerender(<TemplateDataTable result={data} editable={false} onChange={change}/>);expect(screen.queryByRole('dialog')).toBeNull();expect(change).not.toHaveBeenCalled();expect(screen.queryByRole('button',{name:/编辑字段/})).toBeNull()});
