// @vitest-environment jsdom
import React from 'react';
import {render,screen,fireEvent,cleanup,waitFor} from '@testing-library/react';
import {test,expect,vi,afterEach} from 'vitest';
import {TemplateEditor} from './TemplateEditor';
vi.mock('@slidebi/presentation',()=>({
 compileSlide:()=>({elements:[{id:'title',text:'模板标题'},{id:'draft-watermark',text:'草稿'}]}),
 renderSlideSvg:(compiled:any)=>`<svg>${compiled.elements.map((element:any)=>`<text>${element.text}</text>`).join('')}</svg>`,
 FONT_OPTIONS:[],
}));
afterEach(()=>{cleanup();vi.unstubAllGlobals()});
const template={id:'one',name:'营收分析',version:1,visibility:'public',canEdit:false,canDelete:false,example:{businessContext:{background:'观察渠道增长',scenarios:['季度复盘']},slide:{elements:[]},dataSpec:{resultSets:[{id:'r',primaryKey:['name'],fields:[{id:'name',name:'区域',type:'string',nullable:false}],rows:[{name:'华东'}]}]}}};
test('nonowner opens unified template preview without editable inputs',async()=>{vi.stubGlobal('fetch',vi.fn(async()=>new Response(JSON.stringify(template))));render(<TemplateEditor templateId="one" onClose={()=>{}} onSaved={()=>{}}/>);await screen.findByRole('dialog',{name:'营收分析'});expect(screen.getByLabelText('只读预览')).toBeTruthy();expect(screen.queryByRole('textbox')).toBeNull();expect(screen.queryByRole('button',{name:'删除模板'})).toBeNull();expect(screen.getAllByRole('table')).toHaveLength(1);fireEvent.click(screen.getByRole('button',{name:'全屏预览'}));expect(document.querySelector('.template-fullscreen')).toBeTruthy()});
test('template preview omits the draft watermark while retaining page content',async()=>{vi.stubGlobal('fetch',vi.fn(async()=>new Response(JSON.stringify(template))));render(<TemplateEditor templateId="one" onClose={()=>{}} onSaved={()=>{}}/>);await screen.findByRole('dialog',{name:'营收分析'});expect(document.querySelector('.actual-preview')?.textContent).toContain('模板标题');expect(document.querySelector('.actual-preview')?.textContent).not.toContain('草稿')});
test('owner edits schema in single sample table and saves same template version',async()=>{const fetcher=vi.fn(async()=>new Response(JSON.stringify({...template,canEdit:true,canDelete:true})));vi.stubGlobal('fetch',fetcher);const saved=vi.fn();render(<TemplateEditor templateId="one" onClose={()=>{}} onSaved={saved}/>);await screen.findByLabelText('可编辑');fireEvent.click(screen.getByRole('button',{name:'编辑字段 区域'}));fireEvent.change(screen.getByLabelText('字段说明'),{target:{value:'业务区域'}});fireEvent.click(screen.getByRole('button',{name:'应用字段设置'}));fireEvent.change(screen.getByLabelText('适用场景（每行一项）'),{target:{value:'月度复盘\n季度复盘'}});fireEvent.click(screen.getByRole('button',{name:'保存模板'}));await waitFor(()=>expect(saved).toHaveBeenCalled());const call=fetcher.mock.calls.find((c:any)=>c[1]?.method==='PUT') as any;expect(JSON.parse(call[1].body).example.dataSpec.resultSets[0].fields[0].description).toBe('业务区域');expect(JSON.parse(call[1].body).expectedVersion).toBe(1);expect(JSON.parse(call[1].body).example.businessContext.scenarios).toEqual(['月度复盘','季度复盘'])});
test('owner can continue editing or discard from unsaved close dialog',async()=>{vi.stubGlobal('fetch',vi.fn(async()=>new Response(JSON.stringify({...template,canEdit:true}))));const close=vi.fn();render(<TemplateEditor templateId="one" onClose={close} onSaved={()=>{}}/>);await screen.findByLabelText('可编辑');fireEvent.change(screen.getByLabelText('模板名称'),{target:{value:'修改名称'}});fireEvent.click(screen.getByRole('button',{name:'关闭'}));expect(await screen.findByRole('button',{name:'保存并关闭'})).toBeTruthy();fireEvent.click(screen.getByRole('button',{name:'继续编辑'}));expect(close).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('button',{name:'关闭'}));fireEvent.click(screen.getByRole('button',{name:'放弃修改'}));expect(close).toHaveBeenCalled()});
test('failed save-and-close keeps draft and confirmation available for retry',async()=>{vi.stubGlobal('fetch',vi.fn(async(_url:any,options:any)=>options?.method==='PUT'?new Response(JSON.stringify({message:'保存失败'}),{status:500}):new Response(JSON.stringify({...template,canEdit:true}))));const close=vi.fn();render(<TemplateEditor templateId="one" onClose={close} onSaved={()=>{}}/>);await screen.findByLabelText('可编辑');fireEvent.change(screen.getByLabelText('模板名称'),{target:{value:'保留我的修改'}});fireEvent.click(screen.getByRole('button',{name:'关闭'}));fireEvent.click(screen.getByRole('button',{name:'保存并关闭'}));await waitFor(()=>expect(screen.getByRole('button',{name:'保存并关闭'}).hasAttribute('disabled')).toBe(false));expect(screen.getByRole('dialog',{name:'保存模板修改？'})).toBeTruthy();expect((screen.getByLabelText('模板名称') as HTMLInputElement).value).toBe('保留我的修改');expect(close).not.toHaveBeenCalled()});
test('Escape dismisses fullscreen only and readonly users have no save or editing action',async()=>{vi.stubGlobal('fetch',vi.fn(async()=>new Response(JSON.stringify(template))));const close=vi.fn();render(<TemplateEditor templateId="one" onClose={close} onSaved={()=>{}}/>);await screen.findByLabelText('只读预览');fireEvent.click(screen.getByRole('button',{name:'全屏预览'}));fireEvent.keyDown(screen.getByRole('dialog',{name:'模板全屏预览'}),{key:'Escape'});expect(screen.queryByRole('dialog',{name:'模板全屏预览'})).toBeNull();expect(close).not.toHaveBeenCalled();expect(screen.queryByRole('button',{name:'保存模板'})).toBeNull();expect(screen.queryByRole('button',{name:'编辑模板页面'})).toBeNull()});
