import React,{useEffect,useState} from 'react';
import {KeyRound,Plus,ShieldCheck,UserRound,UserRoundCheck,UserRoundX} from 'lucide-react';
import {api,post} from './api';
import {Modal} from './ui';
import {useAuth,type User} from './Auth';
export function UserManagement(){
 const {user:current}=useAuth();const [users,setUsers]=useState<User[]>([]),[error,E]=useState(''),[notice,N]=useState(''),[busy,B]=useState(false),[create,C]=useState(false),[reset,R]=useState<User|null>(null),[username,U]=useState(''),[password,P]=useState(''),[role,S]=useState('user');
 const load=()=>api('/users').then(r=>setUsers(r.items));useEffect(()=>{load().catch(e=>E(e.message));},[]);
 const change=async(user:User,body:any)=>{E('');N('');B(true);try{await api('/users/'+user.id,{method:'PATCH',body:JSON.stringify(body)});await load();N('用户信息已更新');R(null);P('');}catch(e:any){E(e.message);}finally{B(false);}};
 return <><div className="page-heading"><div><h1>用户管理</h1><p className="muted">维护账号、角色与登录状态。</p></div><button className="primary" onClick={()=>{C(true);U('');P('');S('user');E('');}}><Plus size={17}/>新增用户</button></div>{error&&<p role="alert" className="error">{error}</p>}{notice&&<p role="status">{notice}</p>}<div className="user-table"><table><thead><tr><th>用户名</th><th>显示名称</th><th>角色</th><th>状态</th><th>操作</th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td>{u.username}</td><td>{u.displayName}</td><td>{u.role==='admin'?'管理员':'普通用户'}</td><td>{u.disabled?'已停用':'正常'}</td><td><div className="row"><button className="icon" title="重置密码" aria-label={`重置 ${u.username} 密码`} disabled={busy} onClick={()=>{R(u);P('');E('');}}><KeyRound size={17}/></button>{u.id!==current?.id&&<><button className="icon" title={u.role==='admin'?'设为普通用户':'设为管理员'} aria-label={`切换 ${u.username} 角色`} disabled={busy} onClick={()=>{if(window.confirm(`将 ${u.username} 设为${u.role==='admin'?'普通用户':'管理员'}？`))void change(u,{role:u.role==='admin'?'user':'admin'});}}>{u.role==='admin'?<UserRound size={17}/>:<ShieldCheck size={17}/>}</button><button className="icon" title={u.disabled?'启用用户':'停用用户'} aria-label={`${u.disabled?'启用':'停用'} ${u.username}`} disabled={busy} onClick={()=>{if(window.confirm(`${u.disabled?'启用':'停用'} ${u.username}？`))void change(u,{disabled:!u.disabled});}}>{u.disabled?<UserRoundCheck size={17}/>:<UserRoundX size={17}/>}</button></>}</div></td></tr>)}</tbody></table></div>{create&&<Modal title="新增用户" onClose={()=>!busy&&C(false)}><form className="user-form" onSubmit={async e=>{e.preventDefault();B(true);E('');try{await post('/users',{username,password,role});await load();C(false);P('');N('用户已创建');}catch(e:any){E(e.message);}finally{B(false);}}}><label>用户名<input required pattern="[a-zA-Z0-9_.-]{1,100}" value={username} onChange={e=>U(e.target.value)}/></label><label>初始密码<input required type="password" autoComplete="new-password" maxLength={200} value={password} onChange={e=>P(e.target.value)}/></label><label>角色<select value={role} onChange={e=>S(e.target.value)}><option value="user">普通用户</option><option value="admin">管理员</option></select></label>{error&&<p role="alert" className="error">{error}</p>}<button className="primary" disabled={busy}>创建用户</button></form></Modal>}{reset&&<Modal title={`重置 ${reset.username} 密码`} onClose={()=>!busy&&R(null)}><form className="user-form" onSubmit={e=>{e.preventDefault();void change(reset,{password});}}><label>新密码<input required type="password" autoComplete="new-password" maxLength={200} value={password} onChange={e=>P(e.target.value)}/></label><p className="muted">保存后，该用户现有登录会话失效。</p>{error&&<p role="alert" className="error">{error}</p>}<button className="primary" disabled={busy}>保存密码</button></form></Modal>}</>;
}
