import {test,expect,request as playwrightRequest} from '@playwright/test';
import {randomUUID} from 'node:crypto';
test('template draft canvas, fullscreen, keyboard save and unsaved close',async({page,request,browser})=>{
 const name=`R12模板-${randomUUID().slice(0,8)}`;let id='',reader:any;
 try{
 const source=await(await request.get('/api/templates/budget-comparison')).json();
 const response=await request.post('/api/templates/import',{data:{...source,name}});expect(response.ok(),await response.text()).toBe(true);const created=await response.json();id=created.id;
 await page.goto('/library');await page.getByPlaceholder('搜索模板名称').fill(name);await page.getByRole('button',{name:`预览 ${name}`,exact:true}).click();let detail=page.getByRole('dialog',{name,exact:true});
 await expect(detail.getByRole('button',{name:'保存模板',exact:true})).toBeDisabled();await expect(detail.getByText('页面展示调整',{exact:true})).toHaveCount(0);
 await detail.getByRole('button',{name:'全屏预览',exact:true}).click();const full=page.getByRole('dialog',{name:'模板全屏预览',exact:true});await expect(full.locator('svg[role=img]')).toBeVisible();expect(await full.evaluate(e=>e.getBoundingClientRect().width)).toBeGreaterThan(1400);await full.getByRole('button',{name:'关闭',exact:true}).click();
 await detail.getByRole('button',{name:'编辑模板页面',exact:true}).click();const editor=page.getByRole('dialog',{name:'编辑模板页面',exact:true});const bounds=await editor.boundingBox();expect(bounds!.width).toBeGreaterThan(1500);expect(bounds!.height).toBeGreaterThan(970);await page.screenshot({path:'backend/var/verification/review13-template-fullscreen.png'});const text=source.example.slide.elements.find((e:any)=>e.type==='text');await editor.getByRole('button',{name:`选择文字 ${text.id}`,exact:true}).click();await editor.getByRole('textbox',{name:'文字内容',exact:true}).fill('模板画布已修改');await editor.getByLabel('水平位置',{exact:true}).fill('36');await editor.getByRole('button',{name:'完成编辑'}).click();await expect(detail.locator('.actual-preview')).toContainText('模板画布已修改');const saveResponse=page.waitForResponse(r=>r.url().endsWith(`/api/templates/${id}`)&&r.request().method()==='PUT');await page.keyboard.press('Control+s');expect((await saveResponse).ok()).toBe(true);await expect(detail.getByRole('button',{name:'保存模板',exact:true})).toBeDisabled();let saved=await(await request.get(`/api/templates/${id}`)).json();expect(saved.version).toBe(created.version+1);expect(saved.example.slide.elements.find((e:any)=>e.id===text.id).rect.x).toBe(36);
 await detail.getByRole('textbox',{name:'业务背景',exact:true}).fill('尚未保存的业务背景');await detail.getByRole('button',{name:'关闭',exact:true}).click();const confirm=page.getByRole('dialog',{name:'保存模板修改？',exact:true});await expect(confirm).toBeVisible();await confirm.getByRole('button',{name:'继续编辑'}).click();await expect(detail).toBeVisible();await detail.getByRole('button',{name:'关闭',exact:true}).click();await confirm.getByRole('button',{name:'放弃修改'}).click();await expect(detail).toHaveCount(0);saved=await(await request.get(`/api/templates/${id}`)).json();expect(saved.example.businessContext.background).not.toBe('尚未保存的业务背景');
 await page.getByRole('button',{name:`预览 ${name}`,exact:true}).click();detail=page.getByRole('dialog',{name,exact:true});await detail.getByRole('textbox',{name:'业务背景',exact:true}).fill('保存并关闭');await detail.getByRole('button',{name:'切换模板可见性',exact:true}).click();await detail.getByRole('button',{name:'关闭',exact:true}).click();await page.getByRole('button',{name:'保存并关闭',exact:true}).click();await expect(detail).toHaveCount(0);
 const auth=await playwrightRequest.newContext({baseURL:'http://127.0.0.1:5173',storageState:{cookies:[],origins:[]}});await auth.post('/api/auth/login',{data:{username:'mary',password:'mary'}});reader=await browser.newContext({storageState:await auth.storageState()});await auth.dispose();const view=await reader.newPage();await view.goto('http://127.0.0.1:5173/library');await view.getByPlaceholder('搜索模板名称').fill(name);await view.getByRole('button',{name:`预览 ${name}`,exact:true}).click();const readonly=view.getByRole('dialog',{name,exact:true});await expect(readonly.getByRole('button',{name:'编辑模板页面',exact:true})).toHaveCount(0);await expect(readonly.getByRole('textbox')).toHaveCount(0);
 await page.getByRole('button',{name:`预览 ${name}`,exact:true}).click();await expect(page.getByRole('dialog',{name,exact:true}).locator('.actual-preview svg')).toBeVisible();await page.screenshot({path:'backend/var/verification/review12-template-detail.png'});
 }finally{await reader?.close();if(id){const t=await request.get(`/api/templates/${id}`);if(t.ok())await request.delete(`/api/templates/${id}`,{data:{expectedVersion:(await t.json()).version}})}}
});
