import {test,expect} from '@playwright/test';
import {randomUUID} from 'node:crypto';
import JSZip from 'jszip';
test('原生文稿多页：选择导入、独立编辑、排序、导航与PPT导出',async({page,request})=>{
 const ids:string[]=[];const slides:string[]=[];const call=async(path:string,data:any={})=>{const r=await request.post(`/api${path}`,{headers:{'Idempotency-Key':randomUUID()},data});expect(r.ok(),await r.text()).toBe(true);return r.status()===204?null:r.json();};
 try{
 const data=await(await request.get('/api/fixtures/monthly-operations')).json();
 let source=await call('/contents',{title:`来源文稿-${randomUUID().slice(0,6)}`});ids.push(source.id);
 for(const [i,templateId] of ['budget-comparison','monthly-trend'].entries()){const s=await call('/slides/from-import',{dataSpec:data,templateId,title:`源页面-${i+1}`});slides.push(s.id);source=await call(`/contents/${source.id}/pages`,{revision:source.revision,slideId:s.id});}
 let target=await call('/contents',{title:'多页验收文稿'});ids.push(target.id);
 await page.goto(`/contents/${target.id}`);await page.getByRole('button',{name:'新增页面',exact:true}).first().click();await page.getByRole('button',{name:'从其他文稿复制',exact:true}).click();await page.getByRole('combobox',{name:'来源文稿',exact:true}).selectOption(source.id);await page.getByRole('checkbox',{name:'源页面-1',exact:true}).check();await page.getByRole('checkbox',{name:'源页面-2',exact:true}).check();await page.getByRole('button',{name:'导入所选 2 页'}).click();await expect(page.getByLabel('页面名称',{exact:true})).toHaveValue('源页面-1');
 await page.getByLabel('页面名称',{exact:true}).fill('目标独立改名');await page.getByRole('button',{name:'编辑第 2 页 源页面-2'}).click();await expect(page.getByLabel('页面名称',{exact:true})).toHaveValue('源页面-2');await page.getByRole('button',{name:'编辑第 1 页 目标独立改名'}).click();await expect(page.getByLabel('页面名称',{exact:true})).toHaveValue('目标独立改名');expect((await(await request.get(`/api/slides/${source.pages[0].slideId}`)).json()).title).toBe('源页面-1');
 await page.getByRole('button',{name:'编辑第 1 页 目标独立改名'}).press('Alt+ArrowDown');await expect(page.getByRole('button',{name:'编辑第 2 页 目标独立改名'})).toBeVisible();
 await page.screenshot({path:'backend/var/verification/review6-editor.png'});await page.screenshot({path:'backend/var/verification/review7-document-toolbar.png'});await page.getByRole('button',{name:'导航与交付设置',exact:true}).click();await page.getByRole('checkbox',{name:'导航页',exact:true}).check();await page.getByRole('combobox',{name:'交付方式',exact:true}).selectOption('draft');await page.getByRole('dialog',{name:'导航与交付设置'}).getByRole('button',{name:'关闭',exact:true}).click();await page.getByRole('button',{name:'预览文稿',exact:true}).click();await expect(page.getByRole('heading',{name:'文稿预览 · 3 页'})).toBeVisible();await page.screenshot({path:'backend/var/verification/review6-content.png'});const response=page.waitForResponse(r=>r.url().includes(`/decks/${target.id}/export`)&&r.request().method()==='POST');await expect(page.getByRole('dialog').getByRole('button',{name:'导出 PPT',exact:true})).toHaveCount(0);await page.getByRole('dialog').getByRole('button',{name:'关闭',exact:true}).click();await page.getByRole('button',{name:'导出 PPT',exact:true}).click();const job=await(await response).json();const link=page.locator(`a[href="/api/export-jobs/${job.id}/file.pptx"]`);await expect(link).toBeVisible({timeout:20000});const zip=await JSZip.loadAsync(await(await request.get((await link.getAttribute('href'))!)).body());expect(zip.file(/ppt\/slides\/slide\d+\.xml$/)).toHaveLength(3);
 }finally{for(const id of ids)await request.post(`/api/contents/${id}/archive`,{data:{}}).catch(()=>{});for(const id of slides)await request.post(`/api/slides/${id}/archive`,{data:{}}).catch(()=>{});}
});
