import {test,expect,request as playwrightRequest} from '@playwright/test';
import {randomUUID} from 'node:crypto';
test('data directory supports multi-table owner edits, public preview and confirmed batch deletion',async({page,request,browser})=>{
 const name=`R13数据-${randomUUID().slice(0,8)}`;const ids:string[]=[];let folderId='',reader:any;
 try{
  const source=await(await request.get('/api/fixtures/monthly-operations')).json();
  const folder=await request.post('/api/folders',{data:{kind:'data',name:`${name}-目录`}});expect(folder.ok(),await folder.text()).toBe(true);folderId=(await folder.json()).id;
  for(const suffix of ['A','B']){const r=await request.post('/api/datasets',{data:{name:`${name}-${suffix}`,dataSpec:source,preserveResultSets:true}});expect(r.ok(),await r.text()).toBe(true);const d=await r.json();ids.push(d.id);expect((await request.patch(`/api/management/data/${d.id}`,{data:{folderId}})).ok()).toBe(true)}
  await page.goto('/data');await expect(page.getByRole('tree',{name:'数据文件目录'})).toBeVisible();await page.getByRole('button',{name:`打开目录 ${name}-目录`,exact:true}).click();await page.getByRole('button',{name:`预览 ${name}-A`,exact:true}).click();const detail=page.getByRole('region',{name:'数据维护'});
  await expect(detail.getByRole('heading',{name:'数据集',exact:true})).toBeVisible();await expect(page.getByRole('dialog')).toHaveCount(0);const treeBox=await page.getByRole('region',{name:'数据目录'}).boundingBox(),paneBox=await detail.boundingBox();expect(paneBox!.x).toBeGreaterThan(treeBox!.x+treeBox!.width);await expect(detail.locator('.data-detail-section').first().getByRole('table')).toHaveCount(source.resultSets.length);await expect(detail.getByText('来源与链接（只读）')).toHaveCount(0);await expect(detail.getByRole('button',{name:/使用.*模板.*创建页面/})).toHaveCount(0);
  const rs=source.resultSets[0],field=rs.fields.find((f:any)=>f.type==='decimal');await detail.getByRole('button',{name:`编辑字段 ${field.name||field.id}`,exact:true}).first().click();const schema=page.getByRole('dialog',{name:`字段设置 ${field.name||field.id}`,exact:true});await schema.getByLabel('字段说明',{exact:true}).fill('R13数据补充说明');await schema.getByRole('button',{name:'应用字段设置',exact:true}).click();await expect(detail.getByRole('button',{name:'复制数据',exact:true})).toBeDisabled();await detail.getByRole('button',{name:'关闭',exact:true}).click();await page.getByRole('dialog',{name:'保存数据修改？',exact:true}).getByRole('button',{name:'继续编辑'}).click();const savedResponse=page.waitForResponse(r=>r.request().method()==='PUT'&&r.url().includes('/api/datasets/'));await detail.getByRole('button',{name:'保存数据',exact:true}).click();expect((await savedResponse).ok()).toBe(true);await expect(detail.getByRole('button',{name:'保存数据',exact:true})).toBeDisabled();
  const saved=await(await request.get(`/api/datasets/${ids[0]}`)).json();expect(saved.version).toBe(2);expect(saved.dataSpec.resultSets[0].fields.find((f:any)=>f.id===field.id).description).toBe('R13数据补充说明');expect(saved.dataSpec.source).toEqual(source.source);
  await detail.getByRole('button',{name:'历史版本',exact:true}).click();await expect(detail.getByRole('heading',{name:'历史版本 · 最近6版（含当前）'})).toBeVisible();await detail.getByRole('button',{name:'数据表',exact:true}).click();await expect(detail.getByLabel('预览数据表')).toBeVisible();await detail.getByLabel('预览数据表').selectOption(source.resultSets[1].id);await detail.getByRole('button',{name:'私有数据',exact:true}).click();await expect(detail.getByRole('button',{name:'公开数据',exact:true})).toBeVisible();await page.screenshot({path:'backend/var/verification/review13-data-detail.png'});await detail.getByRole('button',{name:'关闭',exact:true}).click();
  const auth=await playwrightRequest.newContext({baseURL:'http://127.0.0.1:5173',storageState:{cookies:[],origins:[]}});expect((await auth.post('/api/auth/login',{data:{username:'mary',password:'mary'}})).ok()).toBe(true);reader=await browser.newContext({storageState:await auth.storageState()});await auth.dispose();const view=await reader.newPage();await view.goto('http://127.0.0.1:5173/data');await view.getByRole('button',{name:`预览 ${name}-A`,exact:true}).click();const readonly=view.getByRole('region',{name:'数据维护'});await expect(readonly.getByRole('button',{name:'保存数据'})).toHaveCount(0);await expect(readonly.getByRole('button',{name:/编辑字段/})).toHaveCount(0);await reader.close();reader=undefined;
  await page.getByRole('checkbox',{name:`选择 ${name}-A`,exact:true}).check();await page.getByRole('checkbox',{name:`选择 ${name}-B`,exact:true}).check();await page.getByRole('button',{name:'批量删除',exact:true}).click();await expect(page.getByRole('dialog',{name:'批量删除数据',exact:true})).toBeVisible();expect((await request.get(`/api/datasets/${ids[0]}`)).ok()).toBe(true);await page.getByRole('button',{name:'确认批量删除',exact:true}).click();await expect(page.getByRole('status')).toContainText('已删除 2 份数据');await expect(page.getByRole('button',{name:`预览 ${name}-A`,exact:true})).toHaveCount(0);await page.screenshot({path:'backend/var/verification/review13-data-directory.png'});
 }finally{await reader?.close();for(const id of ids){const r=await request.get(`/api/datasets/${id}`);if(r.ok())await request.delete(`/api/datasets/${id}`,{headers:{'If-Match':String((await r.json()).version)}})}if(folderId)await request.delete(`/api/folders/${folderId}`)}
});
test('BI refresh configuration stays below each table and saves the named DAX query',async({page,request})=>{
 const name=`R13-BI-${randomUUID().slice(0,8)}`;let id='';try{const r=await request.post('/api/datasets/bi-import',{data:{name,chartId:'chart-demo-budget',splitInputs:false,preserveResultSets:true}});expect(r.ok(),await r.text()).toBe(true);const data=await r.json();id=data.id;await page.goto('/data');await page.getByRole('button',{name:`预览 ${name}`,exact:true}).click();const detail=page.getByRole('region',{name:'数据维护'});await expect(detail.locator('.data-query-placeholder')).toHaveCount(data.dataSpec.resultSets.length);const first=detail.locator('.data-query-placeholder').first();await first.locator('summary').click();await expect(first.getByLabel('模型 ID')).toHaveValue('operations-demo');await first.getByLabel('DAX 查询').fill('EVALUATE ROW("review", 12)');const savedResponse=page.waitForResponse(r=>r.request().method()==='PUT'&&r.url().includes('/api/datasets/'));await detail.getByRole('button',{name:'保存数据',exact:true}).click();expect((await savedResponse).ok()).toBe(true);await expect(detail.getByRole('button',{name:'保存数据',exact:true})).toBeDisabled();const saved=await(await request.get(`/api/datasets/${id}`)).json();expect(saved.refreshConfig.queries[0].text).toBe('EVALUATE ROW("review", 12)');await expect(detail.getByText('BI Studio · Mock · 查询接口预留，当前刷新返回模拟数据')).toBeVisible();}finally{if(id){const r=await request.get(`/api/datasets/${id}`);if(r.ok())await request.delete(`/api/datasets/${id}`,{headers:{'If-Match':String((await r.json()).version)}})}}
});
