import {test,expect,request as playwrightRequest} from '@playwright/test';
import {randomUUID} from 'node:crypto';
test('template owner manages schema and directory while public readers only preview',async({page,request,browser})=>{
 const name=`R11模板-${randomUUID().slice(0,8)}`;let id='',folderId='';let reader:any;
 try{
  const existing=await(await request.get('/api/templates/budget-comparison')).json();
  const folder=await request.post('/api/folders',{data:{kind:'templates',name:`${name}-目录`}});expect(folder.ok(),await folder.text()).toBe(true);folderId=(await folder.json()).id;
  const imported=await request.post('/api/templates/import',{data:{...existing,name,folderId}});expect(imported.ok(),await imported.text()).toBe(true);let template=await imported.json();id=template.id;
  await request.patch(`/api/templates/${id}/metadata`,{data:{expectedVersion:template.version,visibility:'public'}});
  await page.goto('/library');await page.getByRole('button',{name:`目录 ${name}-目录`,exact:true}).click();
  await expect(page.getByRole('navigation',{name:'当前位置'})).toContainText(`${name}-目录`);
  await page.screenshot({path:'backend/var/verification/review11-template-directory.png'});await page.getByRole('button',{name:`预览 ${name}`,exact:true}).click();const detail=page.getByRole('dialog',{name,exact:true});
  await expect(detail.getByLabel('可编辑',{exact:true})).toBeVisible();await expect(detail.locator('.actual-preview svg')).toBeVisible();
  await expect(detail.locator('.actual-preview')).not.toContainText('fixture');
  await expect(detail.getByRole('table')).toHaveCount(existing.example.dataSpec.resultSets.length);
  await detail.getByRole('button',{name:'全屏预览',exact:true}).click();const fullscreen=page.getByRole('dialog',{name:'模板全屏预览',exact:true});await expect(fullscreen.locator('svg[role=img]')).toBeVisible();await fullscreen.getByRole('button',{name:'关闭',exact:true}).click();
  await detail.getByRole('button',{name:'收藏模板',exact:true}).click();await expect(detail.getByRole('button',{name:'收藏模板',exact:true})).toHaveAttribute('title','取消收藏');
  const field=existing.example.dataSpec.resultSets[0].fields.find((f:any)=>f.type==='decimal');await detail.getByRole('button',{name:`编辑字段 ${field.name||field.id}`,exact:true}).first().click();
  const fieldEditor=page.getByRole('dialog',{name:`字段设置 ${field.name||field.id}`,exact:true});await fieldEditor.getByLabel('字段说明',{exact:true}).fill('Review 12 字段说明');await fieldEditor.getByRole('combobox',{name:'字段单位',exact:true}).selectOption('CNY');await fieldEditor.getByLabel('千分位分隔',{exact:true}).check();await fieldEditor.getByRole('combobox',{name:'小数位数',exact:true}).selectOption('2');await fieldEditor.getByRole('button',{name:'应用字段设置'}).click();
  await page.screenshot({path:'backend/var/verification/review11-template-detail.png'});await detail.getByRole('button',{name:'保存模板',exact:true}).click();await expect(detail.getByRole('button',{name:'保存模板',exact:true})).toBeDisabled();await detail.getByRole('button',{name:'关闭',exact:true}).click();
  template=await(await request.get(`/api/templates/${id}`)).json();expect(template.folderId).toBe(folderId);const savedField=template.example.dataSpec.resultSets[0].fields.find((f:any)=>f.id===field.id);expect(savedField.description).toBe('Review 12 字段说明');expect(savedField.unit).toBe('CNY');expect(savedField.displayFormat).toEqual({useGrouping:true,decimalPlaces:2});expect(template.example.dataSpec.resultSets[0].rows).toEqual(existing.example.dataSpec.resultSets[0].rows);
  const auth=await playwrightRequest.newContext({baseURL:'http://127.0.0.1:5173',storageState:{cookies:[],origins:[]}});await auth.post('/api/auth/login',{data:{username:'mary',password:'mary'}});reader=await browser.newContext({storageState:await auth.storageState(),viewport:{width:1512,height:982}});await auth.dispose();const view=await reader.newPage();await view.goto('http://127.0.0.1:5173/library');await view.getByPlaceholder('搜索模板名称').fill(name);await view.getByRole('button',{name:`预览 ${name}`,exact:true}).click();const readonly=view.getByRole('dialog',{name,exact:true});await expect(readonly.getByLabel('只读预览',{exact:true})).toBeVisible();await expect(readonly.getByRole('textbox')).toHaveCount(0);await expect(readonly.getByRole('button',{name:'删除模板'})).toHaveCount(0);await expect(readonly.getByRole('button',{name:/编辑字段/})).toHaveCount(0);await readonly.getByRole('button',{name:'全屏预览'}).click();await expect(view.getByRole('dialog',{name:'模板全屏预览'})).toBeVisible();
  await view.getByRole('dialog',{name:'模板全屏预览'}).getByRole('button',{name:'关闭',exact:true}).click();await view.screenshot({path:'backend/var/verification/review11-template-readonly.png'});
 }finally{await reader?.close();if(id){const t=await request.get(`/api/templates/${id}`);if(t.ok()){const deleted=await request.delete(`/api/templates/${id}`,{data:{expectedVersion:(await t.json()).version}});expect(deleted.ok(),await deleted.text()).toBe(true)}expect((await request.get(`/api/templates/${id}`)).status()).toBe(404)}if(folderId){const deleted=await request.delete(`/api/folders/${folderId}`);expect(deleted.ok(),await deleted.text()).toBe(true);const folders=await(await request.get('/api/folders?kind=templates')).json();expect(folders.items.some((f:any)=>f.id===folderId)).toBe(false)}}
});
