import {createdContent} from './content-helpers';
import {test,expect} from '@playwright/test';import {randomUUID} from 'node:crypto';import JSZip from 'jszip';
const templateIds=['channel-stacked','channel-percent','region-pie','region-donut','revenue-margin-combo','revenue-area','budget-actual-scatter'];
test('二期七种图表：真实模板预览、页面保存与原生PPT下载',async({page,request})=>{
 for(const id of templateIds){let sid='';try{
  const preview=await(await request.post(`/api/templates/${id}/preview`,{data:{}})).json();expect(preview.compatible).toBe(true);
  const managed=await request.post('/api/datasets',{data:{name:`二期图表验收数据-${id}`,dataSpec:preview.dataSpec}});expect(managed.ok()).toBe(true);const dataset=await managed.json();
  const created=await request.post('/api/slides',{headers:{'Idempotency-Key':randomUUID()},data:{datasetId:dataset.id,templateId:id,title:`二期图表验收-${id}`}});expect(created.ok()).toBe(true);sid=(await created.json()).id;
  await page.goto(`/slides/${sid}`);await expect(page.locator('.svg-content [data-chart-type]')).toBeVisible();
  await page.getByRole('button',{name:'确认结论已复核',exact:true}).click();await page.getByRole('button',{name:'导出 PPT',exact:true}).click();await page.getByRole('button',{name:'生成 PPT',exact:true}).click();
  const link=page.getByRole('link',{name:'下载 PPTX',exact:true}).first();await expect(link).toBeVisible({timeout:20000});const [download]=await Promise.all([page.waitForEvent('download'),link.click()]);expect(await download.failure()).toBeNull();expect(download.suggestedFilename()).toMatch(/\.pptx$/);await download.saveAs(`backend/var/verification/review5-${id}.pptx`);
  const zip=await JSZip.loadAsync(await(await request.get((await link.getAttribute('href'))!)).body());expect(zip.file(/ppt\/charts\/chart\d+\.xml$/)).toHaveLength(1);
 }finally{if(sid)await request.post(`/api/slides/${sid}/archive`,{data:{}})}}
});
test('二期编辑：字体、表格、流程、状态、分组及片段可保存并导出',async({page,request})=>{
 let sid='',fid='';const name=`二期编辑验收-${randomUUID().slice(0,6)}`;
 try{const d=await(await request.get('/api/fixtures/monthly-operations')).json();let s=await(await request.post('/api/slides/from-import',{headers:{'Idempotency-Key':randomUUID()},data:{dataSpec:d,templateId:'budget-comparison',title:name}})).json();sid=s.id;s.elements=s.elements.filter((e:any)=>e.id.endsWith('-title'));const changed=await request.put(`/api/slides/${sid}`,{headers:{'If-Match':String(s.revision)},data:s});expect(changed.ok()).toBe(true);
 await page.goto(`/slides/${sid}`);await page.locator('.objects button').first().click();await page.getByRole('button',{name:'样式',exact:true}).click();await page.getByRole('combobox',{name:'字体',exact:true}).selectOption('Arial');await page.getByRole('button',{name:'粗体',exact:true}).click();await page.getByRole('button',{name:'斜体',exact:true}).click();await page.getByRole('combobox',{name:'水平对齐',exact:true}).selectOption('center');await page.getByRole('combobox',{name:'垂直对齐',exact:true}).selectOption('middle');
 await page.getByLabel('插入组件',{exact:true}).selectOption('table');await page.getByRole('dialog').getByRole('button',{name:'插入组件',exact:true}).click();await expect(page.locator('.svg-content')).toContainText('12000000');
 await page.getByLabel('插入组件',{exact:true}).selectOption('process');await page.getByRole('dialog').getByRole('button',{name:'插入组件',exact:true}).click();await page.getByRole('button',{name:'内容',exact:true}).click();await page.getByLabel('Y',{exact:true}).fill('380');
 await page.getByLabel('插入组件',{exact:true}).selectOption('status');await page.getByRole('dialog').getByLabel('完成度（%）').fill('75');await page.getByRole('dialog').getByRole('button',{name:'插入组件',exact:true}).click();await page.getByLabel('Y',{exact:true}).fill('450');
 await page.locator('.objects').getByRole('button',{name:'T 流程条',exact:true}).click({modifiers:['Shift']});await page.getByRole('button',{name:'成组',exact:true}).click();await page.getByRole('button',{name:'保存',exact:true}).click();await expect(page.locator('.save-status')).toContainText('已保存');
 s=await(await request.get(`/api/slides/${sid}`)).json();const group=s.elements.filter((e:any)=>e.groupId);expect(group).toHaveLength(2);expect(group[0].groupId).toBe(group[1].groupId);expect(s.elements[0].style).toMatchObject({fontFace:'Arial',bold:true,italic:true,align:'center',valign:'middle'});
 await page.getByRole('button',{name:'组件片段',exact:true}).click();await page.getByLabel('片段名称').fill(name);await page.getByRole('button',{name:'保存所选为片段'}).click();await expect(page.getByRole('dialog').getByRole('heading',{name,exact:true})).toBeVisible();fid=(await(await request.get('/api/fragments')).json()).items.find((f:any)=>f.name===name).id;
 await page.getByRole('dialog').getByRole('button',{name:'关闭',exact:true}).click();await page.reload();await expect(page.locator('.svg-content')).toContainText('75%');await page.screenshot({path:'backend/var/verification/review5-editor.png'});
 await page.getByRole('button',{name:'确认结论已复核',exact:true}).click();await page.getByRole('button',{name:'导出 PPT',exact:true}).click();await page.getByRole('button',{name:'生成 PPT',exact:true}).click();const link=page.getByRole('link',{name:'下载 PPTX',exact:true}).first();await expect(link).toBeVisible({timeout:20000});const [download]=await Promise.all([page.waitForEvent('download'),link.click()]);await download.saveAs('backend/var/verification/review5-editor.pptx');const zip=await JSZip.loadAsync(await(await request.get((await link.getAttribute('href'))!)).body());const xml=await zip.file('ppt/slides/slide1.xml')!.async('string');expect(xml).toContain('<a:tbl>');expect(xml).toContain('Arial');expect(xml).toContain('75%');
 }finally{if(fid)await request.post(`/api/fragments/${fid}/archive`,{data:{}}).catch(()=>{});if(sid)await request.post(`/api/slides/${sid}/archive`,{data:{}}).catch(()=>{})}
});
test('新模板字段映射与片段插入使用目标页面当前数据',async({page,request})=>{
 let sid='',fid='',contentId='';const title=`绑定验收-${randomUUID().slice(0,6)}`;
 try{const preview=await(await request.post('/api/templates/revenue-margin-combo/preview',{data:{}})).json();const data=preview.dataSpec;data.chartHints=[];
 await page.goto('/slides/new');await page.getByLabel('JSON 数据').fill(JSON.stringify(data));await page.getByRole('button',{name:'校验数据',exact:true}).click();await page.getByRole('button',{name:'下一步：选择模板 →'}).click();await page.getByRole('dialog').getByRole('button',{name:/^收入与利润率双轴/}).click();await page.getByRole('button',{name:'下一步：确认绑定 →'}).click();await page.getByRole('combobox',{name:'结果集',exact:true}).selectOption('profitTrend');await expect(page.getByRole('combobox',{name:'柱指标 1',exact:true})).toHaveValue('revenue');await expect(page.getByRole('combobox',{name:'线指标 1',exact:true})).toHaveValue('margin');await page.getByLabel('页面名称').fill(title);await page.getByRole('button',{name:'创建页面并进入编辑器'}).click();({slideId:sid,contentId}=await createdContent(page,request));
 await page.locator('.objects').getByRole('button',{name:'▥ 业务图表',exact:true}).click();await page.getByRole('button',{name:'组件片段',exact:true}).click();await page.getByLabel('片段名称').fill(title);await page.getByRole('button',{name:'保存所选为片段'}).click();const insert=page.getByRole('button',{name:`使用当前主题插入 ${title}`,exact:true});await expect(insert).toBeVisible();fid=(await(await request.get('/api/fragments')).json()).items.find((f:any)=>f.name===title).id;await insert.click();await page.getByRole('button',{name:'保存',exact:true}).click();await expect(page.locator('.save-status')).toContainText('已保存');const saved=await(await request.get(`/api/slides/${sid}`)).json();const charts=saved.elements.filter((e:any)=>e.type==='chart');expect(charts).toHaveLength(2);expect(charts[0].bindingRef).not.toBe(charts[1].bindingRef);expect(saved.bindings[charts[1].bindingRef].roles.lineSeries).toEqual(['margin']);await page.reload();await expect(page.locator('.svg-content [data-chart-type="combo"]')).toHaveCount(2);
 }finally{if(contentId)await request.post(`/api/contents/${contentId}/archive`,{data:{}}).catch(()=>{});if(fid)await request.post(`/api/fragments/${fid}/archive`,{data:{}}).catch(()=>{});if(sid)await request.post(`/api/slides/${sid}/archive`,{data:{}}).catch(()=>{})}
});
